// The Mazí course. One lesson a day, taken together, in order.
// Each lesson: a few new items, one grammar point, and a short dialogue for the two of you.
// Items: letters use k: 'letter' (with their sound written out); words and phrases have
// el (Greek), en (English) and tm (Telugu meaning). Pronunciation is generated by translit.js.
// Dialogue lines: [role, Greek, English]. "___" means "say your own name".
window.MAZI_COURSE = {
  phases: [
    { n: 0, title: 'Letters & sounds', span: 'Lessons 1–10 · about 2 weeks', goal: 'Read any Greek word aloud.' },
    { n: 1, title: 'Home Greek', span: 'Lessons 11–90 · about 3 months', goal: 'Everyday talk at home: greetings, meals, feelings, prayer, time.' },
    { n: 2, title: 'Your day', span: 'Lessons 91–180 · about 3 months', goal: 'Talk about yesterday, today and tomorrow.' },
    { n: 3, title: 'Bible bridge', span: 'Lessons 181–270 · about 3 months', goal: 'Read simple New Testament verses in Koine Greek.' },
    { n: 4, title: 'Reading together', span: 'Lesson 271 onward · year 2', goal: 'Read the Gospel of John together.' }
  ],

  units: [
    { phase: 0, title: 'Letters & sounds', from: 1, to: 10 },
    { phase: 1, title: 'You and me', from: 11, to: 20 },
    { phase: 1, title: 'Home and food', from: 21, to: 30 },
    { phase: 1, title: 'Our daily routine', from: 31, to: 40, soon: true },
    { phase: 1, title: 'Days, time and plans', from: 41, to: 50, soon: true },
    { phase: 1, title: 'Faith at home', from: 51, to: 60, soon: true },
    { phase: 1, title: 'Family and people', from: 61, to: 70, soon: true },
    { phase: 1, title: 'Out and about', from: 71, to: 80, soon: true },
    { phase: 1, title: 'Checkpoint: three months', from: 81, to: 90, soon: true },
    { phase: 2, title: 'Past, future and stories', from: 91, to: 180, soon: true },
    { phase: 3, title: 'Koine forms and first verses', from: 181, to: 270, soon: true },
    { phase: 4, title: 'The Gospel of John', from: 271, to: 360, soon: true }
  ],

  lessons: [
    /* ---------------- Unit: Letters & sounds ---------------- */
    {
      n: 1, title: 'Five vowel sounds', goal: 'Read the Greek vowels and say hello.',
      items: [
        { k: 'letter', up: 'Α', el: 'α', say: 'a', te: 'అ', en: 'a as in "father"' },
        { k: 'letter', up: 'Ε', el: 'ε', say: 'e', te: 'ఎ', en: 'e as in "pen"' },
        { k: 'letter', up: 'Ο', el: 'ο', say: 'o', te: 'ఒ', en: 'o, short and round' },
        { k: 'letter', up: 'Ω', el: 'ω', say: 'o', te: 'ఒ', en: 'o, same sound as ο' },
        { k: 'letter', up: 'Ι', el: 'ι', say: 'i', te: 'ఇ', en: 'i as in "machine", short' },
        { k: 'letter', up: 'Η', el: 'η', say: 'i', te: 'ఇ', en: 'i, same sound as ι' },
        { k: 'letter', up: 'Υ', el: 'υ', say: 'i', te: 'ఇ', en: 'i, also the same sound' },
        { el: 'Γεια σου', en: 'Hi / Bye (to one person)', tm: 'హాయ్ / వెళ్ళొస్తా' }
      ],
      grammar: {
        title: 'Seven letters, five sounds',
        body: [
          'Greek writes the i sound three ways (ι, η, υ) and the o sound two ways (ο, ω). Today they sound exactly the same. The different spellings come from ancient Greek.',
          'Every Greek vowel is short and clean. There are no English-style glides like the "ay" in "day".'
        ],
        te: 'Greek vowels sound like Telugu అ ఎ ఇ ఒ ఉ, always short.',
        ex: [{ el: 'Γεια σου', en: 'Hi' }]
      },
      dialogue: {
        title: 'First hello', tip: 'Say it three times: happy, sleepy, then surprised.',
        lines: [['A', 'Γεια σου!', 'Hi!'], ['B', 'Γεια σου!', 'Hi!']]
      }
    },
    {
      n: 2, title: 'Friendly consonants', goal: 'Read your first real words.',
      items: [
        { k: 'letter', up: 'Κ', el: 'κ', say: 'k', te: 'క', en: 'k, no puff of air' },
        { k: 'letter', up: 'Μ', el: 'μ', say: 'm', te: 'మ', en: 'm' },
        { k: 'letter', up: 'Ν', el: 'ν', say: 'n', te: 'న', en: 'n (it looks like v, but it is n)' },
        { k: 'letter', up: 'Τ', el: 'τ', say: 't', te: 'త', en: 't, the soft Telugu త, not ట' },
        { k: 'letter', up: 'Π', el: 'π', say: 'p', te: 'ప', en: 'p' },
        { k: 'letter', up: 'Λ', el: 'λ', say: 'l', te: 'ల', en: 'l' },
        { k: 'letter', up: 'Σ', el: 'σ / ς', say: 's', te: 'స', en: 's (ς only at the end of a word)' },
        { el: 'καλό', en: 'good', tm: 'మంచిది' },
        { el: 'όνομα', en: 'name', tm: 'పేరు' },
        { el: 'Καλημέρα', en: 'Good morning', tm: 'శుభోదయం' }
      ],
      grammar: {
        title: 'Read it as you see it',
        body: [
          'Greek is spelled the way it sounds. Say each letter in order and you have the word.',
          'The small mark ( ΄ ) shows the loud syllable: όνομα is Ó-no-ma, καλό is ka-LÓ.'
        ],
        te: 'Watch out for ν. It looks like the English v, but it is న.',
        ex: [{ el: 'όνομα', en: 'name' }, { el: 'καλό', en: 'good' }]
      },
      dialogue: {
        title: 'Good morning', tip: 'Say Καλημέρα to each other tomorrow before anything else.',
        lines: [['A', 'Καλημέρα!', 'Good morning!'], ['B', 'Καλημέρα! Γεια σου!', 'Good morning! Hi!']]
      }
    },
    {
      n: 3, title: 'Letters that fool you', goal: 'Read ρ β γ δ correctly, and say thank you.',
      items: [
        { k: 'letter', up: 'Ρ', el: 'ρ', say: 'r', te: 'ర', en: 'r (looks like p, but it is r)' },
        { k: 'letter', up: 'Β', el: 'β', say: 'v', te: 'వ', en: 'v, never b' },
        { k: 'letter', up: 'Γ', el: 'γ', say: 'gh / y', te: 'గ / య', en: 'a soft, breathy g; y before e and i' },
        { k: 'letter', up: 'Δ', el: 'δ', say: 'dh', te: 'ద', en: 'th as in "this"' },
        { el: 'νερό', en: 'water', tm: 'నీళ్ళు' },
        { el: 'γάλα', en: 'milk', tm: 'పాలు' },
        { el: 'δρόμος', en: 'road', tm: 'దారి' },
        { el: 'Ευχαριστώ', en: 'Thank you', tm: 'ధన్యవాదాలు' },
        { el: 'Παρακαλώ', en: 'Please / You\'re welcome', tm: 'దయచేసి / పర్వాలేదు' }
      ],
      grammar: {
        title: 'False friends',
        body: [
          'Four letters look like English letters but sound different: ρ is r, β is v, γ is a soft g, and δ is the "th" in "this".',
          'Before e and i sounds, γ turns into a y: γεια is "ya".'
        ],
        te: 'Telugu has no letter for δ, so Mazí writes it as ద. Say it with the tongue touching the top teeth. ρ is exactly Telugu ర.',
        ex: [{ el: 'νερό', en: 'water' }, { el: 'δρόμος', en: 'road' }]
      },
      dialogue: {
        title: 'A glass of water', tip: 'Pass something to each other at dinner and use ευχαριστώ and παρακαλώ.',
        lines: [['A', 'Νερό;', 'Water?'], ['B', 'Ευχαριστώ!', 'Thank you!'], ['A', 'Παρακαλώ.', 'You\'re welcome.']]
      }
    },
    {
      n: 4, title: 'New shapes', goal: 'Read θ φ χ ψ ξ ζ, and say yes or no.',
      items: [
        { k: 'letter', up: 'Θ', el: 'θ', say: 'th', te: 'థ', en: 'th as in "think"' },
        { k: 'letter', up: 'Φ', el: 'φ', say: 'f', te: 'ఫ', en: 'a real f, as in "fan"' },
        { k: 'letter', up: 'Χ', el: 'χ', say: 'kh', te: 'ఖ', en: 'a throaty h, like "loch"' },
        { k: 'letter', up: 'Ψ', el: 'ψ', say: 'ps', te: 'ప్స', en: 'ps in one letter' },
        { k: 'letter', up: 'Ξ', el: 'ξ', say: 'ks', te: 'క్స', en: 'ks in one letter' },
        { k: 'letter', up: 'Ζ', el: 'ζ', say: 'z', te: 'జ', en: 'z as in "zoo"' },
        { el: 'Θεός', en: 'God', tm: 'దేవుడు' },
        { el: 'ψωμί', en: 'bread', tm: 'రొట్టె' },
        { el: 'ζωή', en: 'life', tm: 'జీవితం' },
        { el: 'Ναι / Όχι', en: 'Yes / No', tm: 'అవును / కాదు', note: 'Careful: ναι sounds like "ne" but means yes.' }
      ],
      grammar: {
        title: 'One letter, two English letters',
        body: [
          'Greek has single letters for sounds English spells with two: θ (th), φ (f), χ (kh), ψ (ps), ξ (ks).',
          'ψ is said as ps even at the start of a word: ψωμί is pso-MÍ.'
        ],
        te: 'θ is not quite థ: put your tongue between your teeth and let air flow, with no puff. φ is a real f, lips on teeth. ζ is the Hindi ज़, not Telugu జ.',
        ex: [{ el: 'Θεός', en: 'God' }, { el: 'ψωμί', en: 'bread' }]
      },
      dialogue: {
        title: 'Yes or no', tip: 'Offer each other three things at the table. Answer only ναι or όχι.',
        lines: [['A', 'Ψωμί;', 'Bread?'], ['B', 'Ναι, ευχαριστώ.', 'Yes, thank you.'], ['A', 'Γάλα;', 'Milk?'], ['B', 'Όχι, ευχαριστώ.', 'No, thank you.']]
      }
    },
    {
      n: 5, title: 'The loud syllable', goal: 'Use the accent mark, and say "I love you".',
      items: [
        { el: 'πότε', en: 'when', tm: 'ఎప్పుడు' },
        { el: 'ποτέ', en: 'never', tm: 'ఎన్నడూ' },
        { el: 'τι', en: 'what', tm: 'ఏమిటి' },
        { el: 'Σ\' αγαπώ', en: 'I love you', tm: 'నిన్ను ప్రేమిస్తున్నాను', note: 'αγαπώ is the verb behind αγάπη, the love of 1 Corinthians 13.' },
        { el: 'Κι εγώ', en: 'Me too', tm: 'నేను కూడా' }
      ],
      grammar: {
        title: 'Stress changes the word',
        body: [
          'Every Greek word of two or more syllables has one accent mark. Say that syllable louder.',
          'Moving the stress can change the meaning: πότε (PÓ-te) is "when", but ποτέ (po-TÉ) is "never".',
          'The Greek question mark looks like a semicolon: Πότε; means "When?"'
        ],
        te: 'Telugu stress is gentle. Greek stress is strong. In Mazí\'s Telugu script, a long vowel (ా ీ ూ ే ో) marks the loud syllable.',
        ex: [{ el: 'Πότε;', en: 'When?' }, { el: 'Ποτέ!', en: 'Never!' }]
      },
      dialogue: {
        title: 'Three little words', tip: 'Say this before you sleep tonight.',
        lines: [['A', 'Σ\' αγαπώ.', 'I love you.'], ['B', 'Κι εγώ σ\' αγαπώ.', 'I love you too.']]
      }
    },
    {
      n: 6, title: 'Two letters, one sound', goal: 'Read ου ει οι αι, and ask how someone is.',
      items: [
        { k: 'letter', up: 'ΟΥ', el: 'ου', say: 'u', te: 'ఉ', en: 'u as in "put"' },
        { k: 'letter', up: 'ΕΙ', el: 'ει', say: 'i', te: 'ఇ', en: 'i' },
        { k: 'letter', up: 'ΟΙ', el: 'οι', say: 'i', te: 'ఇ', en: 'i' },
        { k: 'letter', up: 'ΑΙ', el: 'αι', say: 'e', te: 'ఎ', en: 'e' },
        { el: 'ουρανός', en: 'sky, heaven', tm: 'ఆకాశం, పరలోకం' },
        { el: 'και', en: 'and', tm: 'మరియు' },
        { el: 'Τι κάνεις;', en: 'How are you?', tm: 'ఎలా ఉన్నావు?' },
        { el: 'Καλά, εσύ;', en: 'Good, and you?', tm: 'బాగున్నాను, నువ్వు?' }
      ],
      grammar: {
        title: 'Letter pairs',
        body: [
          'Four vowel pairs make a single sound: ου = u, ει = i, οι = i, αι = e.',
          'If the accent sits on the first letter, the pair splits into two sounds: τσάι (tea) is TSÁ-i.'
        ],
        te: 'So Greek now has five ways to write the ఇ sound: ι, η, υ, ει, οι.',
        ex: [{ el: 'ουρανός', en: 'heaven' }, { el: 'Τι κάνεις;', en: 'How are you?' }]
      },
      dialogue: {
        title: 'How are you?', tip: 'Ask this every evening this week.',
        lines: [['A', 'Γεια σου! Τι κάνεις;', 'Hi! How are you?'], ['B', 'Καλά, εσύ;', 'Good, and you?'], ['A', 'Καλά, ευχαριστώ.', 'Good, thank you.']]
      }
    },
    {
      n: 7, title: 'v or f: αυ and ευ', goal: 'Read αυ and ευ, and say sorry.',
      items: [
        { k: 'letter', up: 'ΑΥ', el: 'αυ', say: 'av / af', te: 'అవ్ / అఫ్', en: 'av, or af before hard sounds' },
        { k: 'letter', up: 'ΕΥ', el: 'ευ', say: 'ev / ef', te: 'ఎవ్ / ఎఫ్', en: 'ev, or ef before hard sounds' },
        { el: 'αύριο', en: 'tomorrow', tm: 'రేపు' },
        { el: 'αυτό', en: 'this, it', tm: 'ఇది' },
        { el: 'Ευαγγέλιο', en: 'Gospel', tm: 'సువార్త' },
        { el: 'Συγγνώμη', en: 'Sorry', tm: 'క్షమించు' },
        { el: 'Δεν πειράζει', en: 'No problem, it\'s fine', tm: 'పర్వాలేదు' },
        { el: 'Τα λέμε αύριο', en: 'See you tomorrow', tm: 'రేపు కలుద్దాం' }
      ],
      grammar: {
        title: 'When υ becomes v or f',
        body: [
          'After α or ε, the letter υ sounds like v: αύριο (ÁV-ri-o), Ευαγγέλιο (ev-an-GÉ-li-o).',
          'Before a hard sound (κ π τ θ φ χ σ ξ ψ) it becomes f: αυτό (af-TÓ), ευχαριστώ (ef-kha-ri-STÓ).'
        ],
        te: 'You already say ευχαριστώ with f. Now you know why.',
        ex: [{ el: 'αύριο', en: 'tomorrow' }, { el: 'αυτό', en: 'this' }]
      },
      dialogue: {
        title: 'Oops', tip: 'Bump into each other on purpose, then say it.',
        lines: [['A', 'Συγγνώμη!', 'Sorry!'], ['B', 'Δεν πειράζει.', 'No problem.'], ['A', 'Τα λέμε αύριο!', 'See you tomorrow!'], ['B', 'Τα λέμε!', 'See you!']]
      }
    },
    {
      n: 8, title: 'b, d and g', goal: 'Read μπ ντ γκ γγ τσ τζ.',
      items: [
        { k: 'letter', up: 'ΜΠ', el: 'μπ', say: 'b', te: 'బ', en: 'b' },
        { k: 'letter', up: 'ΝΤ', el: 'ντ', say: 'd', te: 'డ', en: 'd' },
        { k: 'letter', up: 'ΓΚ', el: 'γκ', say: 'g', te: 'గ', en: 'g as in "go"' },
        { k: 'letter', up: 'ΓΓ', el: 'γγ', say: 'ng', te: 'ంగ', en: 'ng as in "finger"' },
        { k: 'letter', up: 'ΤΣ', el: 'τσ', say: 'ts', te: 'త్స', en: 'ts' },
        { k: 'letter', up: 'ΤΖ', el: 'τζ', say: 'dz', te: 'ద్జ', en: 'dz' },
        { el: 'μπαμπάς', en: 'dad', tm: 'నాన్న' },
        { el: 'μαμά', en: 'mum', tm: 'అమ్మ' },
        { el: 'τσάι', en: 'tea', tm: 'టీ' },
        { el: 'άγγελος', en: 'angel', tm: 'దేవదూత' },
        { el: 'Πάμε!', en: 'Let\'s go!', tm: 'వెళ్దాం పద!' }
      ],
      grammar: {
        title: 'Borrowed sounds',
        body: [
          'Modern Greek has no single letter for b, d or g, so it uses pairs: μπ = b, ντ = d, γκ = g.',
          'γγ is ng, as in άγγελος (ÁN-ge-los). This is where the English word "angel" comes from.'
        ],
        te: 'The Greek d in ντ is soft, between Telugu ద and డ.',
        ex: [{ el: 'μπαμπάς', en: 'dad' }, { el: 'άγγελος', en: 'angel' }]
      },
      dialogue: {
        title: 'Tea time', tip: 'Make tea together and use Πάμε! to start.',
        lines: [['A', 'Τσάι;', 'Tea?'], ['B', 'Ναι! Πάμε!', 'Yes! Let\'s go!']]
      }
    },
    {
      n: 9, title: 'Greek you already know', goal: 'Read long words, and capital letters.',
      items: [
        { el: 'τηλέφωνο', en: 'telephone', tm: 'ఫోను' },
        { el: 'μουσική', en: 'music', tm: 'సంగీతం' },
        { el: 'θέατρο', en: 'theatre', tm: 'నాటకశాల' },
        { el: 'πρόβλημα', en: 'problem', tm: 'సమస్య' },
        { el: 'ιδέα', en: 'idea', tm: 'ఆలోచన' },
        { el: 'Δόξα τω Θεώ', en: 'Glory to God (thank God)', tm: 'దేవునికి మహిమ', note: 'Greeks say this every day, like "thank God". τω Θεώ is an old form straight from the Bible.' }
      ],
      grammar: {
        title: 'Capital letters',
        body: [
          'Capitals are the same letters, just bigger: Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω.',
          'Signs and headings are often written all in capitals, without accent marks: ΑΘΗΝΑ is Αθήνα (Athens).'
        ],
        te: 'English took thousands of words from Greek: telephone, music, theatre, problem, idea. You already know them.',
        ex: [{ el: 'ΘΕΑΤΡΟ', en: 'THEATRE' }, { el: 'Δόξα τω Θεώ!', en: 'Thank God!' }]
      },
      dialogue: {
        title: 'Thank God', tip: 'Use δόξα τω Θεώ whenever something good happens today.',
        lines: [['A', 'Τι κάνεις;', 'How are you?'], ['B', 'Καλά, δόξα τω Θεώ! Εσύ;', 'Good, thank God! You?'], ['A', 'Καλά, ευχαριστώ.', 'Good, thank you.']]
      }
    },
    {
      n: 10, title: 'Checkpoint: read it all', goal: 'Read any Greek word aloud.',
      items: [
        { el: 'Ελλάδα', en: 'Greece', tm: 'గ్రీసు' },
        { el: 'Ιησούς', en: 'Jesus', tm: 'యేసు' },
        { el: 'Χριστός', en: 'Christ', tm: 'క్రీస్తు' },
        { el: 'Βίβλος', en: 'Bible', tm: 'బైబిల్' },
        { el: 'Αγάπη μου', en: 'My love', tm: 'నా ప్రేమా' },
        { el: 'Καληνύχτα', en: 'Good night', tm: 'శుభ రాత్రి' },
        { el: 'Ο Θεός μαζί σου', en: 'God be with you', tm: 'దేవుడు నీకు తోడై ఉండును గాక' }
      ],
      grammar: {
        title: 'What you can do now',
        body: [
          'You know every Greek letter and every letter pair. You can read any Greek word aloud, even ones you don\'t understand yet.',
          'From the next lesson, you start building real sentences.'
        ],
        te: 'Try reading a Greek sign or a Greek Bible verse aloud. You will be surprised.',
        ex: [{ el: 'Ιησούς Χριστός', en: 'Jesus Christ' }]
      },
      dialogue: {
        title: 'Good night', tip: 'Make this your good-night routine from now on.',
        lines: [['A', 'Καληνύχτα, αγάπη μου.', 'Good night, my love.'], ['B', 'Καληνύχτα. Ο Θεός μαζί σου.', 'Good night. God be with you.'], ['A', 'Αμήν.', 'Amen.']]
      }
    },

    /* ---------------- Unit: You and me ---------------- */
    {
      n: 11, title: 'I am, you are', goal: 'Say who you are and ask a name.',
      items: [
        { el: 'εγώ', en: 'I', tm: 'నేను' },
        { el: 'εσύ', en: 'you', tm: 'నువ్వు' },
        { el: 'είμαι', en: 'I am', tm: '(నేను) ఉన్నాను' },
        { el: 'είσαι', en: 'you are', tm: '(నువ్వు) ఉన్నావు' },
        { el: 'Με λένε…', en: 'My name is…', tm: 'నా పేరు…' },
        { el: 'Πώς σε λένε;', en: 'What\'s your name?', tm: 'నీ పేరేమిటి?' },
        { el: 'Χαίρω πολύ', en: 'Nice to meet you', tm: 'మిమ్మల్ని కలవడం సంతోషం' }
      ],
      grammar: {
        title: 'Dropping "I" and "you"',
        body: [
          'είμαι already means "I am" and είσαι already means "you are". Greek usually leaves out εγώ and εσύ.',
          'Use εγώ or εσύ only for emphasis: Εγώ είμαι καλά. Εσύ; ("I am fine. And you?")'
        ],
        te: 'Telugu does the same: ఉన్నాను already means "I am", so నేను is optional.',
        ex: [{ el: 'Είμαι καλά.', en: 'I am fine.' }, { el: 'Είσαι καλά;', en: 'Are you fine?' }]
      },
      dialogue: {
        title: 'Strangers again', tip: 'Pretend you are meeting for the first time. Use your real names.',
        lines: [['A', 'Γεια σου! Με λένε ___. Πώς σε λένε;', 'Hi! My name is ___. What\'s your name?'], ['B', 'Με λένε ___.', 'My name is ___.'], ['A', 'Χαίρω πολύ!', 'Nice to meet you!'], ['B', 'Κι εγώ!', 'Me too!']]
      }
    },
    {
      n: 12, title: 'He, she and "the"', goal: 'Introduce your husband or wife.',
      items: [
        { el: 'αυτός', en: 'he', tm: 'అతను' },
        { el: 'αυτή', en: 'she', tm: 'ఆమె' },
        { el: 'είναι', en: 'he / she / it is', tm: 'ఉన్నాడు / ఉంది' },
        { el: 'ο άντρας μου', en: 'my husband', tm: 'నా భర్త', note: 'άντρας means both "man" and "husband".' },
        { el: 'η γυναίκα μου', en: 'my wife', tm: 'నా భార్య', note: 'γυναίκα means both "woman" and "wife".' },
        { el: 'ο / η', en: 'the (for him / for her)', tm: 'పురుష / స్త్రీ పదాల ముందు "the"' }
      ],
      grammar: {
        title: 'ο for him, η for her',
        body: [
          '"The" changes with the word: ο for masculine words (ο άντρας), η for feminine words (η γυναίκα).',
          'μου after a word means "my": ο άντρας μου, η γυναίκα μου.'
        ],
        te: 'Telugu shows he or she in the verb (వచ్చాడు / వచ్చింది). Greek shows it in "the": ο / η.',
        ex: [{ el: 'Αυτή είναι η γυναίκα μου.', en: 'This is my wife.' }, { el: 'Αυτός είναι ο άντρας μου.', en: 'This is my husband.' }]
      },
      dialogue: {
        title: 'Meet my spouse', tip: 'Introduce each other to an imaginary guest (a chair works).',
        lines: [['A', 'Αυτή είναι η γυναίκα μου.', 'This is my wife.'], ['B', 'Και αυτός είναι ο άντρας μου.', 'And this is my husband.'], ['A', 'Χαίρω πολύ!', 'Nice to meet you!']]
      }
    },
    {
      n: 13, title: 'How do you feel?', goal: 'Say how you feel, as a man or as a woman.',
      items: [
        { el: 'Πώς είσαι;', en: 'How are you (feeling)?', tm: 'ఎలా ఉన్నావు?' },
        { el: 'χαρούμενος / χαρούμενη', en: 'happy (him / her)', tm: 'సంతోషంగా' },
        { el: 'κουρασμένος / κουρασμένη', en: 'tired (him / her)', tm: 'అలసిపోయి' },
        { el: 'λυπημένος / λυπημένη', en: 'sad (him / her)', tm: 'బాధగా' },
        { el: 'ήρεμος / ήρεμη', en: 'calm (him / her)', tm: 'ప్రశాంతంగా' },
        { el: 'άρρωστος / άρρωστη', en: 'sick (him / her)', tm: 'జబ్బుగా' }
      ],
      grammar: {
        title: '-ος for him, -η for her',
        body: [
          'Describing words change with who they describe. A man says Είμαι κουρασμένος. A woman says Είμαι κουρασμένη.',
          'In the lists, the first form is for him and the second for her.'
        ],
        te: 'Just like Telugu అలసిపోయాడు / అలసిపోయింది, the ending shows man or woman.',
        ex: [{ el: 'Είμαι χαρούμενος.', en: 'I am happy (man).' }, { el: 'Είμαι χαρούμενη.', en: 'I am happy (woman).' }]
      },
      dialogue: {
        title: 'Checking in', tip: 'Use your own form: -ος for him, -η for her.',
        lines: [['A', 'Πώς είσαι;', 'How are you?'], ['B', 'Είμαι κουρασμένος / κουρασμένη. Εσύ;', 'I\'m tired. You?'], ['A', 'Είμαι χαρούμενος / χαρούμενη!', 'I\'m happy!']]
      }
    },
    {
      n: 14, title: 'Question words', goal: 'Ask what, where, how, who and why.',
      items: [
        { el: 'πού', en: 'where', tm: 'ఎక్కడ' },
        { el: 'πώς', en: 'how', tm: 'ఎలా' },
        { el: 'ποιος / ποια', en: 'who (him / her)', tm: 'ఎవరు' },
        { el: 'γιατί', en: 'why; because', tm: 'ఎందుకు; ఎందుకంటే' },
        { el: 'εδώ / εκεί', en: 'here / there', tm: 'ఇక్కడ / అక్కడ' },
        { el: 'Τι είναι αυτό;', en: 'What is this?', tm: 'ఇది ఏమిటి?' }
      ],
      grammar: {
        title: 'Asking questions',
        body: [
          'Question words go first: Πού είσαι; (Where are you?) Τι είναι αυτό; (What is this?)',
          'For yes/no questions, keep the normal sentence and raise your voice at the end: Είσαι καλά; (Are you OK?)',
          'Watch the accent: πού means "where", but που without an accent means "that / who" in the middle of a sentence.'
        ],
        te: 'Telugu adds -ఆ to make a question (బాగున్నావా?). Greek just raises the voice.',
        ex: [{ el: 'Πού είσαι;', en: 'Where are you?' }, { el: 'Γιατί;', en: 'Why?' }]
      },
      dialogue: {
        title: 'What is this?', tip: 'Point at things around you and ask Τι είναι αυτό; Answer with words you know.',
        lines: [['A', 'Τι είναι αυτό;', 'What is this?'], ['B', 'Είναι νερό.', 'It\'s water.'], ['A', 'Πού είναι το ψωμί;', 'Where is the bread?'], ['B', 'Εκεί!', 'There!']]
      }
    },
    {
      n: 15, title: 'Not, maybe, of course', goal: 'Say no politely and make negative sentences.',
      items: [
        { el: 'δεν', en: 'not', tm: 'కాదు / లేదు' },
        { el: 'ξέρω', en: 'I know', tm: 'నాకు తెలుసు' },
        { el: 'Δεν ξέρω', en: 'I don\'t know', tm: 'నాకు తెలియదు' },
        { el: 'ίσως', en: 'maybe', tm: 'బహుశా' },
        { el: 'βέβαια', en: 'of course', tm: 'తప్పకుండా' },
        { el: 'Εντάξει', en: 'OK', tm: 'సరే' }
      ],
      grammar: {
        title: 'δεν goes before the verb',
        body: [
          'To say "not", put δεν right before the verb: Είμαι κουρασμένος → Δεν είμαι κουρασμένος.',
          'Όχι answers a question ("No"). δεν makes a sentence negative.'
        ],
        te: 'Telugu puts "not" at the end (తెలియదు). Greek puts δεν at the front of the verb.',
        ex: [{ el: 'Δεν ξέρω.', en: 'I don\'t know.' }, { el: 'Δεν είμαι κουρασμένη.', en: 'I\'m not tired (woman).' }]
      },
      dialogue: {
        title: 'Not tired', tip: 'Ask each other three yes/no questions. Answer with δεν.',
        lines: [['A', 'Είσαι κουρασμένη;', 'Are you tired?'], ['B', 'Όχι, δεν είμαι κουρασμένη. Εσύ;', 'No, I\'m not tired. You?'], ['A', 'Δεν ξέρω… ίσως!', 'I don\'t know… maybe!'], ['B', 'Εντάξει.', 'OK.']]
      }
    },
    {
      n: 16, title: 'We are together', goal: 'Use we, you (plural) and they.',
      items: [
        { el: 'εμείς', en: 'we', tm: 'మేము / మనం' },
        { el: 'εσείς', en: 'you (plural, or polite)', tm: 'మీరు' },
        { el: 'αυτοί', en: 'they', tm: 'వారు' },
        { el: 'είμαστε', en: 'we are', tm: '(మనం) ఉన్నాం' },
        { el: 'είστε', en: 'you are (plural)', tm: '(మీరు) ఉన్నారు' },
        { el: 'μαζί', en: 'together', tm: 'కలిసి', note: 'This is the name of the app.' }
      ],
      grammar: {
        title: 'The whole verb "to be"',
        body: [
          'εγώ είμαι · εσύ είσαι · αυτός / αυτή είναι',
          'εμείς είμαστε · εσείς είστε · αυτοί είναι',
          'είναι means both "he/she is" and "they are".'
        ],
        te: 'εσείς is also the polite "you" for elders, like Telugu మీరు.',
        ex: [{ el: 'Είμαστε μαζί.', en: 'We are together.' }, { el: 'Πού είστε;', en: 'Where are you (all)?' }]
      },
      dialogue: {
        title: 'Together', tip: 'Hold hands for this one.',
        lines: [['A', 'Είμαστε μαζί.', 'We are together.'], ['B', 'Ναι, είμαστε μαζί. Δόξα τω Θεώ!', 'Yes, we are together. Thank God!']]
      }
    },
    {
      n: 17, title: 'Numbers 1 to 5', goal: 'Count to five and ask how many.',
      items: [
        { el: 'ένα', en: 'one', tm: 'ఒకటి' },
        { el: 'δύο', en: 'two', tm: 'రెండు' },
        { el: 'τρία', en: 'three', tm: 'మూడు' },
        { el: 'τέσσερα', en: 'four', tm: 'నాలుగు' },
        { el: 'πέντε', en: 'five', tm: 'ఐదు' },
        { el: 'Πόσα;', en: 'How many?', tm: 'ఎన్ని?' }
      ],
      grammar: {
        title: 'Cousins of Sanskrit',
        body: [
          'Greek and Sanskrit come from the same ancient family, and the numbers show it.',
          'δύο and ద్వి, τρία and త్రి, πέντε and పంచ.'
        ],
        te: 'You already know these roots from Telugu words like ద్వితీయ, త్రికోణం and పంచాంగం.',
        ex: [{ el: 'ένα, δύο, τρία', en: 'one, two, three' }]
      },
      dialogue: {
        title: 'How many?', tip: 'Count spoons, cups and fingers together.',
        lines: [['A', 'Πόσα;', 'How many?'], ['B', 'Τρία.', 'Three.'], ['A', 'Τρία; Όχι, τέσσερα!', 'Three? No, four!']]
      }
    },
    {
      n: 18, title: 'Numbers 6 to 10', goal: 'Count to ten and say the time.',
      items: [
        { el: 'έξι', en: 'six', tm: 'ఆరు' },
        { el: 'εφτά', en: 'seven', tm: 'ఏడు' },
        { el: 'οχτώ', en: 'eight', tm: 'ఎనిమిది' },
        { el: 'εννιά', en: 'nine', tm: 'తొమ్మిది' },
        { el: 'δέκα', en: 'ten', tm: 'పది' },
        { el: 'Τι ώρα είναι;', en: 'What time is it?', tm: 'టైం ఎంత అయింది?' }
      ],
      grammar: {
        title: 'Telling the hour',
        body: [
          'Say the hour with είναι: Είναι εφτά. (It\'s seven.)',
          'You will also see επτά, οκτώ and εννέα. These are the formal spellings of the same numbers.'
        ],
        te: 'More Sanskrit cousins: έξι and షట్, εφτά and సప్త, οχτώ and అష్ట, εννιά and నవ, δέκα and దశ.',
        ex: [{ el: 'Είναι δέκα.', en: 'It\'s ten o\'clock.' }]
      },
      dialogue: {
        title: 'Time to go', tip: 'Ask the time three times today.',
        lines: [['A', 'Τι ώρα είναι;', 'What time is it?'], ['B', 'Είναι εφτά.', 'It\'s seven.'], ['A', 'Εφτά; Πάμε!', 'Seven? Let\'s go!']]
      }
    },
    {
      n: 19, title: 'Words of love', goal: 'Say sweet things to each other.',
      items: [
        { el: 'καρδιά μου', en: 'my heart (sweetheart)', tm: 'నా ప్రాణమా' },
        { el: 'μωρό μου', en: 'my baby', tm: 'నా బంగారం' },
        { el: 'Μου λείπεις', en: 'I miss you', tm: 'నువ్వు గుర్తొస్తున్నావు' },
        { el: 'Είσαι όμορφη / όμορφος', en: 'You are beautiful (to her / to him)', tm: 'నువ్వు అందంగా ఉన్నావు' },
        { el: 'Είμαι τυχερός / τυχερή', en: 'I am lucky (man / woman)', tm: 'నేను అదృష్టవంతుడిని / అదృష్టవంతురాలిని' },
        { el: 'Φιλάκια', en: 'Kisses (to sign off)', tm: 'ముద్దులు' }
      ],
      grammar: {
        title: 'μου means "my" and "to me"',
        body: [
          'After a word, μου means "my": η καρδιά μου (my heart), το μωρό μου (my baby).',
          'Before a verb, μου means "to me": Μου λείπεις is literally "You are missing to me".'
        ],
        te: 'Just like Telugu నాకు గుర్తొస్తున్నావు, "to me" comes first.',
        ex: [{ el: 'Μου λείπεις, καρδιά μου.', en: 'I miss you, sweetheart.' }]
      },
      dialogue: {
        title: 'Missing you', tip: 'Send one of these lines on WhatsApp today, in Greek.',
        lines: [['A', 'Μου λείπεις, καρδιά μου.', 'I miss you, sweetheart.'], ['B', 'Κι εσύ μου λείπεις.', 'I miss you too.'], ['A', 'Σ\' αγαπώ.', 'I love you.'], ['B', 'Κι εγώ σ\' αγαπώ. Φιλάκια!', 'I love you too. Kisses!']]
      }
    },
    {
      n: 20, title: 'Checkpoint: breakfast talk', goal: 'Have a whole breakfast conversation in Greek.',
      items: [
        { el: 'Κοιμήθηκες καλά;', en: 'Did you sleep well?', tm: 'బాగా నిద్రపోయావా?' },
        { el: 'πολύ', en: 'very, a lot', tm: 'చాలా' },
        { el: 'Ναι, πολύ καλά', en: 'Yes, very well', tm: 'అవును, చాలా బాగా' },
        { el: 'Καλή όρεξη', en: 'Enjoy your meal', tm: 'హాయిగా తినండి' }
      ],
      grammar: {
        title: 'What you can do now',
        body: [
          'You can greet, introduce each other, say how you feel, ask questions, say no, count to ten, tell the hour and say sweet things.',
          'Read the whole dialogue below twice, swapping roles the second time.'
        ],
        te: 'This is real Greek. Greek couples say exactly these things every morning.',
        ex: [{ el: 'Κοιμήθηκες καλά;', en: 'Did you sleep well?' }]
      },
      dialogue: {
        title: 'Breakfast', tip: 'Do it at the real breakfast table tomorrow.',
        lines: [
          ['A', 'Καλημέρα, αγάπη μου!', 'Good morning, my love!'],
          ['B', 'Καλημέρα!', 'Good morning!'],
          ['A', 'Κοιμήθηκες καλά;', 'Did you sleep well?'],
          ['B', 'Ναι, πολύ καλά. Εσύ;', 'Yes, very well. You?'],
          ['A', 'Όχι πολύ. Είμαι κουρασμένος / κουρασμένη.', 'Not really. I\'m tired.'],
          ['B', 'Τσάι;', 'Tea?'],
          ['A', 'Ναι, ευχαριστώ!', 'Yes, thank you!'],
          ['B', 'Παρακαλώ. Καλή όρεξη!', 'You\'re welcome. Enjoy!']
        ]
      }
    },

    /* ---------------- Unit: Home and food ---------------- */
    {
      n: 21, title: 'I have', goal: 'Say what you have and ask if someone has time.',
      items: [
        { el: 'έχω', en: 'I have', tm: 'నా దగ్గర ఉంది' },
        { el: 'έχεις', en: 'you have', tm: 'నీ దగ్గర ఉంది' },
        { el: 'έχει', en: 'he / she has', tm: 'అతని / ఆమె దగ్గర ఉంది' },
        { el: 'σπίτι', en: 'house, home', tm: 'ఇల్లు' },
        { el: 'χρόνο', en: 'time (to spare)', tm: 'సమయం' },
        { el: 'Έχεις χρόνο;', en: 'Do you have time?', tm: 'నీకు సమయం ఉందా?' }
      ],
      grammar: {
        title: 'Verbs that end in -ω',
        body: [
          'Most Greek verbs end in -ω, and the ending tells you who: έχω (I have), έχεις (you have), έχει (he/she has).',
          'Plural: έχουμε (we have), έχετε (you have), έχουν (they have).'
        ],
        te: 'Telugu says నా దగ్గర ఉంది, "with me there is". Greek simply says έχω, "I have".',
        ex: [{ el: 'Δεν έχω χρόνο.', en: 'I don\'t have time.' }]
      },
      dialogue: {
        title: 'Coffee date', tip: 'Actually go for coffee this week, and ask in Greek.',
        lines: [['A', 'Έχεις χρόνο;', 'Do you have time?'], ['B', 'Ναι, έχω.', 'Yes, I do.'], ['A', 'Πάμε για καφέ;', 'Shall we go for coffee?'], ['B', 'Πάμε!', 'Let\'s go!']]
      }
    },
    {
      n: 22, title: 'The: ο, η, το', goal: 'Name things at home with the right "the".',
      items: [
        { el: 'ο καφές', en: 'the coffee', tm: 'కాఫీ' },
        { el: 'η πόρτα', en: 'the door', tm: 'తలుపు' },
        { el: 'το νερό', en: 'the water', tm: 'నీళ్ళు' },
        { el: 'η κουζίνα', en: 'the kitchen', tm: 'వంటగది' },
        { el: 'το παράθυρο', en: 'the window', tm: 'కిటికీ' },
        { el: 'το σπίτι', en: 'the house', tm: 'ఇల్లు' }
      ],
      grammar: {
        title: 'Three genders',
        body: [
          'Every Greek noun is masculine (ο), feminine (η) or neuter (το), even things.',
          'The ending usually tells you: -ος, -ας, -ης → ο · -α, -η → η · -ο, -ι, -μα → το.',
          'Always learn a new word together with its ο, η or το.'
        ],
        te: 'Telugu calls things అది (neuter). Greek gives every noun a gender, like Hindi does.',
        ex: [{ el: 'Πού είναι το νερό;', en: 'Where is the water?' }, { el: 'Η πόρτα είναι εκεί.', en: 'The door is there.' }]
      },
      dialogue: {
        title: 'Where is it?', tip: 'Walk around the house and ask about each thing.',
        lines: [['A', 'Πού είναι ο καφές;', 'Where is the coffee?'], ['B', 'Εκεί, στην κουζίνα.', 'There, in the kitchen.'], ['A', 'Ευχαριστώ!', 'Thanks!']]
      }
    },
    {
      n: 23, title: 'I want', goal: 'Say what you want, and offer drinks.',
      items: [
        { el: 'θέλω', en: 'I want', tm: 'నాకు కావాలి' },
        { el: 'θέλεις', en: 'you want', tm: 'నీకు కావాలా' },
        { el: 'Θέλεις καφέ ή τσάι;', en: 'Do you want coffee or tea?', tm: 'కాఫీ కావాలా, టీ కావాలా?' },
        { el: 'λίγο', en: 'a little', tm: 'కొంచెం' },
        { el: 'ζάχαρη', en: 'sugar', tm: 'చక్కెర' },
        { el: 'Δεν θέλω', en: 'I don\'t want', tm: 'నాకు వద్దు' }
      ],
      grammar: {
        title: 'The "object" form',
        body: [
          'When a masculine word is the thing you want, its final ς drops: ο καφές → Θέλω καφέ.',
          'Feminine and neuter words stay the same: Θέλω ζάχαρη. Θέλω νερό.',
          'ή (with an accent) means "or".'
        ],
        te: 'Like Telugu adding -ని to the object (కాఫీని), Greek changes the ending of the thing.',
        ex: [{ el: 'Θέλω καφέ.', en: 'I want coffee.' }, { el: 'Θέλεις ζάχαρη;', en: 'Do you want sugar?' }]
      },
      dialogue: {
        title: 'Coffee or tea?', tip: 'Make each other a drink tonight, asking only in Greek.',
        lines: [['A', 'Θέλεις καφέ ή τσάι;', 'Coffee or tea?'], ['B', 'Καφέ, παρακαλώ.', 'Coffee, please.'], ['A', 'Ζάχαρη;', 'Sugar?'], ['B', 'Λίγο.', 'A little.']]
      }
    },
    {
      n: 24, title: 'Food', goal: 'Name everyday foods and decide what to eat.',
      items: [
        { el: 'ρύζι', en: 'rice', tm: 'అన్నం / బియ్యం' },
        { el: 'κοτόπουλο', en: 'chicken', tm: 'చికెన్' },
        { el: 'αυγό / αυγά', en: 'egg / eggs', tm: 'గుడ్డు / గుడ్లు' },
        { el: 'ψάρι', en: 'fish', tm: 'చేప' },
        { el: 'λαχανικά', en: 'vegetables', tm: 'కూరగాయలు' },
        { el: 'φρούτα', en: 'fruit', tm: 'పండ్లు' },
        { el: 'Τι θέλεις να φάμε;', en: 'What shall we eat?', tm: 'ఏం తిందాం?' }
      ],
      grammar: {
        title: 'Plurals of το-words',
        body: [
          'Neuter words ending in -ο change to -α: το αυγό → τα αυγά.',
          'Words ending in -ι add -α: το ψάρι → τα ψάρια.',
          'The plural of το is τα.'
        ],
        te: 'Telugu adds -లు (గుడ్లు). Greek changes the ending instead.',
        ex: [{ el: 'Θέλω δύο αυγά.', en: 'I want two eggs.' }]
      },
      dialogue: {
        title: 'Dinner plans', tip: 'Decide tomorrow\'s dinner in Greek.',
        lines: [['A', 'Τι θέλεις να φάμε;', 'What shall we eat?'], ['B', 'Ρύζι και κοτόπουλο.', 'Rice and chicken.'], ['A', 'Και λαχανικά;', 'And vegetables?'], ['B', 'Ναι, βέβαια!', 'Yes, of course!']]
      }
    },
    {
      n: 25, title: 'At the table', goal: 'Talk at the dinner table.',
      items: [
        { el: 'Πεινάω', en: 'I\'m hungry', tm: 'నాకు ఆకలిగా ఉంది' },
        { el: 'Διψάω', en: 'I\'m thirsty', tm: 'నాకు దాహంగా ఉంది' },
        { el: 'Το φαγητό είναι έτοιμο', en: 'The food is ready', tm: 'భోజనం సిద్ధంగా ఉంది' },
        { el: 'Πολύ νόστιμο!', en: 'Very tasty!', tm: 'చాలా రుచిగా ఉంది!' },
        { el: 'Κι άλλο;', en: 'More?', tm: 'ఇంకా కావాలా?' },
        { el: 'Χόρτασα', en: 'I\'m full', tm: 'కడుపు నిండింది' }
      ],
      grammar: {
        title: 'Verbs that end in -άω',
        body: [
          'Some verbs end in -άω: πεινάω (I\'m hungry), διψάω (I\'m thirsty), αγαπάω (I love).',
          'They go: πεινάω, πεινάς, πεινάει, πεινάμε, πεινάτε, πεινάνε.'
        ],
        te: 'Greek says "I hunger" with one verb, where Telugu says నాకు ఆకలిగా ఉంది.',
        ex: [{ el: 'Πεινάς;', en: 'Are you hungry?' }]
      },
      dialogue: {
        title: 'Dinner is ready', tip: 'Use these at tonight\'s dinner.',
        lines: [['A', 'Πεινάω!', 'I\'m hungry!'], ['B', 'Το φαγητό είναι έτοιμο.', 'The food is ready.'], ['A', 'Πολύ νόστιμο!', 'Very tasty!'], ['B', 'Κι άλλο;', 'More?'], ['A', 'Όχι, ευχαριστώ. Χόρτασα.', 'No, thanks. I\'m full.']]
      }
    },
    {
      n: 26, title: 'Where in the house?', goal: 'Say where you are at home.',
      items: [
        { el: 'το σαλόνι', en: 'the living room', tm: 'హాలు' },
        { el: 'η κρεβατοκάμαρα', en: 'the bedroom', tm: 'పడకగది' },
        { el: 'το μπάνιο', en: 'the bathroom', tm: 'స్నానాల గది' },
        { el: 'ο κήπος', en: 'the garden', tm: 'తోట' },
        { el: 'στο / στην', en: 'in the, at the', tm: '…లో' },
        { el: 'Έλα εδώ!', en: 'Come here!', tm: 'ఇక్కడికి రా!' }
      ],
      grammar: {
        title: 'σε + the = στο, στην',
        body: [
          'σε means "in / at / to". It joins with "the": σε + το = στο, σε + την = στην, σε + τον = στον.',
          'Είμαι στο σαλόνι. (I\'m in the living room.) Είμαι στην κουζίνα. (I\'m in the kitchen.)'
        ],
        te: 'Like Telugu -లో: వంటగదిలో = στην κουζίνα.',
        ex: [{ el: 'Είμαι στον κήπο.', en: 'I\'m in the garden.' }]
      },
      dialogue: {
        title: 'Where are you?', tip: 'Call each other from different rooms, in Greek only.',
        lines: [['A', 'Πού είσαι;', 'Where are you?'], ['B', 'Στην κουζίνα. Εσύ;', 'In the kitchen. You?'], ['A', 'Στο σαλόνι. Έλα εδώ!', 'In the living room. Come here!']]
      }
    },
    {
      n: 27, title: 'Things at home', goal: 'Find things around the house.',
      items: [
        { el: 'το τραπέζι', en: 'the table', tm: 'బల్ల' },
        { el: 'η καρέκλα', en: 'the chair', tm: 'కుర్చీ' },
        { el: 'το κρεβάτι', en: 'the bed', tm: 'మంచం' },
        { el: 'τα κλειδιά', en: 'the keys', tm: 'తాళాలు' },
        { el: 'το τηλέφωνο', en: 'the phone', tm: 'ఫోను' },
        { el: 'η τσάντα', en: 'the bag', tm: 'సంచి' }
      ],
      grammar: {
        title: 'Plurals of η-words',
        body: [
          'Feminine words ending in -α or -η change to -ες: η καρέκλα → οι καρέκλες.',
          'The plural of ο and η is οι: οι καρέκλες. The plural of το is τα: τα κλειδιά.'
        ],
        te: 'Greek has two plural "the" words: οι (for ο and η words) and τα (for το words).',
        ex: [{ el: 'Πού είναι τα κλειδιά;', en: 'Where are the keys?' }]
      },
      dialogue: {
        title: 'Lost keys', tip: 'Hide the keys and ask for them in Greek.',
        lines: [['A', 'Πού είναι τα κλειδιά;', 'Where are the keys?'], ['B', 'Στο τραπέζι.', 'On the table.'], ['A', 'Και το τηλέφωνό μου;', 'And my phone?'], ['B', 'Στην τσάντα σου!', 'In your bag!']]
      }
    },
    {
      n: 28, title: 'Big, small, hot, cold', goal: 'Describe things.',
      items: [
        { el: 'μεγάλος / μεγάλη / μεγάλο', en: 'big', tm: 'పెద్ద' },
        { el: 'μικρός / μικρή / μικρό', en: 'small', tm: 'చిన్న' },
        { el: 'ζεστός / ζεστή / ζεστό', en: 'hot', tm: 'వేడి' },
        { el: 'κρύος / κρύα / κρύο', en: 'cold', tm: 'చల్లని' },
        { el: 'καινούργιος / καινούργια / καινούργιο', en: 'new', tm: 'కొత్త' },
        { el: 'Ωραία!', en: 'Great! Lovely!', tm: 'బాగుంది!' }
      ],
      grammar: {
        title: 'Describing words match',
        body: [
          'A describing word takes the ending of its noun: ο μεγάλος κήπος, η μεγάλη κουζίνα, το μεγάλο σπίτι.',
          'Some feminine forms end in -α instead of -η: κρύα, καινούργια.'
        ],
        te: 'Telugu పెద్ద never changes. Greek μεγάλος changes to match ο, η or το.',
        ex: [{ el: 'Το τσάι είναι κρύο.', en: 'The tea is cold.' }]
      },
      dialogue: {
        title: 'Cold tea', tip: 'Describe three things on the table.',
        lines: [['A', 'Το τσάι είναι κρύο!', 'The tea is cold!'], ['B', 'Συγγνώμη! Θέλεις ζεστό τσάι;', 'Sorry! Do you want hot tea?'], ['A', 'Ναι, ευχαριστώ.', 'Yes, thank you.'], ['B', 'Ωραία!', 'Great!']]
      }
    },
    {
      n: 29, title: 'Cooking together', goal: 'Talk while you cook.',
      items: [
        { el: 'μαγειρεύω', en: 'I cook', tm: 'నేను వండుతాను' },
        { el: 'τρώω', en: 'I eat', tm: 'నేను తింటాను' },
        { el: 'πίνω', en: 'I drink', tm: 'నేను తాగుతాను' },
        { el: 'πλένω', en: 'I wash', tm: 'నేను కడుగుతాను' },
        { el: 'Να βοηθήσω;', en: 'Shall I help?', tm: 'సహాయం చేయనా?' },
        { el: 'Τι μαγειρεύεις;', en: 'What are you cooking?', tm: 'ఏం వండుతున్నావు?' }
      ],
      grammar: {
        title: 'The full present tense',
        body: [
          'μαγειρεύω (I cook) · μαγειρεύεις (you cook) · μαγειρεύει (he/she cooks)',
          'μαγειρεύουμε (we cook) · μαγειρεύετε (you cook) · μαγειρεύουν (they cook)',
          'The same endings work for most verbs: πλένω, πλένεις, πλένει…'
        ],
        te: 'Telugu verbs change by person too: వండుతాను, వండుతావు, వండుతాడు.',
        ex: [{ el: 'Μαγειρεύουμε μαζί.', en: 'We cook together.' }]
      },
      dialogue: {
        title: 'In the kitchen', tip: 'Cook one meal this week speaking only Greek.',
        lines: [['A', 'Τι μαγειρεύεις;', 'What are you cooking?'], ['B', 'Ρύζι και ψάρι.', 'Rice and fish.'], ['A', 'Να βοηθήσω;', 'Shall I help?'], ['B', 'Ναι! Πλένεις τα λαχανικά;', 'Yes! Will you wash the vegetables?'], ['A', 'Εντάξει.', 'OK.']]
      }
    },
    {
      n: 30, title: 'Checkpoint: dinner at home', goal: 'Have a full evening conversation.',
      items: [
        { el: 'Γύρισα!', en: 'I\'m home! (I\'m back)', tm: 'నేను వచ్చేశాను!' },
        { el: 'Καλώς ήρθες', en: 'Welcome (home)', tm: 'స్వాగతం' },
        { el: 'Πώς πήγε η μέρα σου;', en: 'How was your day?', tm: 'నీ రోజు ఎలా గడిచింది?' },
        { el: 'αλλά', en: 'but', tm: 'కానీ' },
        { el: 'Ας προσευχηθούμε', en: 'Let\'s pray', tm: 'ప్రార్థన చేద్దాం' }
      ],
      grammar: {
        title: 'What you can do now',
        body: [
          'You can talk about home, food, where things are and what you want, and describe things.',
          'That is enough Greek for a whole evening at home. Read the dialogue twice, swapping roles.'
        ],
        te: 'From here, the course moves on to your daily routine.',
        ex: [{ el: 'Πώς πήγε η μέρα σου;', en: 'How was your day?' }]
      },
      dialogue: {
        title: 'Evening at home', tip: 'Do this tonight when one of you comes home.',
        lines: [
          ['A', 'Γύρισα!', 'I\'m home!'],
          ['B', 'Καλώς ήρθες, αγάπη μου! Πώς πήγε η μέρα σου;', 'Welcome home, my love! How was your day?'],
          ['A', 'Καλά, αλλά είμαι κουρασμένος / κουρασμένη. Πεινάω!', 'Good, but I\'m tired. I\'m hungry!'],
          ['B', 'Το φαγητό είναι έτοιμο. Ρύζι και κοτόπουλο.', 'The food is ready. Rice and chicken.'],
          ['A', 'Ωραία! Ας προσευχηθούμε.', 'Lovely! Let\'s pray.'],
          ['B', 'Αμήν. Καλή όρεξη!', 'Amen. Enjoy your meal!']
        ]
      }
    }
  ]
};
