// The Mazí course. One lesson a day, taken together, in order.
// Each lesson: a few new items, one grammar point, and a short dialogue for the two of you.
// Items: letters use k: 'letter' (with their sound written out); words and phrases have
// el (Greek), en (English) and tm (Telugu meaning). Pronunciation is generated by translit.js.
// Dialogue lines: [role, Greek, English]. "___" means "say your own name".
window.MAZI_COURSE = {
  phases: [
    { n: 0, title: 'Letters & sounds', span: 'Lessons 1–10 · about 2 weeks', goal: 'Read any Greek word aloud.' },
    { n: 1, title: 'Home Greek', span: 'Lessons 11–90 · about 3 months', goal: 'Everyday talk at home: greetings, meals, feelings, prayer, time.' },
    { n: 2, title: 'Your day', span: 'Lessons 91–180 · about 3 months', goal: 'Talk about yesterday, today and tomorrow.' },
    { n: 3, title: 'Bible bridge', span: 'Lessons 181–270 · about 3 months', goal: 'Read simple New Testament verses in Koine Greek.' },
    { n: 4, title: 'Reading together', span: 'Lesson 271 onward · year 2', goal: 'Read the Gospel of John together.' }
  ],

  units: [
    { phase: 0, title: 'Letters & sounds', from: 1, to: 10 },
    { phase: 1, title: 'You and me', from: 11, to: 20 },
    { phase: 1, title: 'Home and food', from: 21, to: 30 },
    { phase: 1, title: 'Our daily routine', from: 31, to: 40, soon: true },
    { phase: 1, title: 'Days, time and plans', from: 41, to: 50, soon: true },
    { phase: 1, title: 'Faith at home', from: 51, to: 60, soon: true },
    { phase: 1, title: 'Family and people', from: 61, to: 70, soon: true },
    { phase: 1, title: 'Out and about', from: 71, to: 80, soon: true },
    { phase: 1, title: 'Checkpoint: three months', from: 81, to: 90, soon: true },
    { phase: 2, title: 'Past, future and stories', from: 91, to: 180, soon: true },
    { phase: 3, title: 'Koine forms and first verses', from: 181, to: 270, soon: true },
    { phase: 4, title: 'The Gospel of John', from: 271, to: 360, soon: true }
  ],

  lessons: [
    /* ---------------- Unit: Letters & sounds ---------------- */
    {
      n: 1, title: 'Five vowel sounds', goal: 'Read the Greek vowels and say hello.',
      items: [
        { k: 'letter', up: 'Α', el: 'α', say: 'a', te: 'అ', en: 'a as in "father"' },
        { k: 'letter', up: 'Ε', el: 'ε', say: 'e', te: 'ఎ', en: 'e as in "pen"' },
        { k: 'letter', up: 'Ο', el: 'ο', say: 'o', te: 'ఒ', en: 'o, short and round' },
        { k: 'letter', up: 'Ω', el: 'ω', say: 'o', te: 'ఒ', en: 'o, same sound as ο' },
        { k: 'letter', up: 'Ι', el: 'ι', say: 'i', te: 'ఇ', en: 'i as in "machine", short' },
        { k: 'letter', up: 'Η', el: 'η', say: 'i', te: 'ఇ', en: 'i, same sound as ι' },
        { k: 'letter', up: 'Υ', el: 'υ', say: 'i', te: 'ఇ', en: 'i, also the same sound' },
        { el: 'Γεια σου', en: 'Hi / Bye (to one person)', tm: 'హాయ్ / వెళ్ళొస్తా' }
      ],
      grammar: {
        title: 'Seven letters, five sounds',
        body: [
          'Greek writes the i sound three ways (ι, η, υ) and the o sound two ways (ο, ω). Today they sound exactly the same. The different spellings come from ancient Greek.',
          'Every Greek vowel is short and clean. There are no English-style glides like the "ay" in "day".'
        ],
        te: 'Greek vowels sound like Telugu అ ఎ ఇ ఒ ఉ, always short.',
        ex: [{ el: 'Γεια σου', en: 'Hi' }]
      },
      dialogue: {
        title: 'First hello', tip: 'Say it three times: happy, sleepy, then surprised.',
        lines: [['A', 'Γεια σου!', 'Hi!'], ['B', 'Γεια σου!', 'Hi!']]
      }
    },
    {
      n: 2, title: 'Friendly consonants', goal: 'Read your first real words.',
      items: [
        { k: 'letter', up: 'Κ', el: 'κ', say: 'k', te: 'క', en: 'k, no puff of air' },
        { k: 'letter', up: 'Μ', el: 'μ', say: 'm', te: 'మ', en: 'm' },
        { k: 'letter', up: 'Ν', el: 'ν', say: 'n', te: 'న', en: 'n (it looks like v, but it is n)' },
        { k: 'letter', up: 'Τ', el: 'τ', say: 't', te: 'త', en: 't, the soft Telugu త, not ట' },
        { k: 'letter', up: 'Π', el: 'π', say: 'p', te: 'ప', en: 'p' },
        { k: 'letter', up: 'Λ', el: 'λ', say: 'l', te: 'ల', en: 'l' },
        { k: 'letter', up: 'Σ', el: 'σ / ς', say: 's', te: 'స', en: 's (ς only at the end of a word)' },
        { el: 'καλό', en: 'good', tm: 'మంచిది' },
        { el: 'όνομα', en: 'name', tm: 'పేరు' },
        { el: 'Καλημέρα', en: 'Good morning', tm: 'శుభోదయం' }
      ],
      grammar: {
        title: 'Read it as you see it',
        body: [
          'Greek is spelled the way it sounds. Say each letter in order and you have the word.',
          'The small mark ( ΄ ) shows the loud syllable: όνομα is Ó-no-ma, καλό is ka-LÓ.'
        ],
        te: 'Watch out for ν. It looks like the English v, but it is న.',
        ex: [{ el: 'όνομα', en: 'name' }, { el: 'καλό', en: 'good' }]
      },
      dialogue: {
        title: 'Good morning', tip: 'Say Καλημέρα to each other tomorrow before anything else.',
        lines: [['A', 'Καλημέρα!', 'Good morning!'], ['B', 'Καλημέρα! Γεια σου!', 'Good morning! Hi!']]
      }
    },
    {
      n: 3, title: 'Letters that fool you', goal: 'Read ρ β γ δ correctly, and say thank you.',
      items: [
        { k: 'letter', up: 'Ρ', el: 'ρ', say: 'r', te: 'ర', en: 'r (looks like p, but it is r)' },
        { k: 'letter', up: 'Β', el: 'β', say: 'v', te: 'వ', en: 'v, never b' },
        { k: 'letter', up: 'Γ', el: 'γ', say: 'gh / y', te: 'గ / య', en: 'a soft, breathy g; y before e and i' },
        { k: 'letter', up: 'Δ', el: 'δ', say: 'dh', te: 'ద', en: 'th as in "this"' },
        { el: 'νερό', en: 'water', tm: 'నీళ్ళు' },
        { el: 'γάλα', en: 'milk', tm: 'పాలు' },
        { el: 'δρόμος', en: 'road', tm: 'దారి' },
        { el: 'Ευχαριστώ', en: 'Thank you', tm: 'ధన్యవాదాలు' },
        { el: 'Παρακαλώ', en: 'Please / You\'re welcome', tm: 'దయచేసి / పర్వాలేదు' }
      ],
      grammar: {
        title: 'False friends',
        body: [
          'Four letters look like English letters but sound different: ρ is r, β is v, γ is a soft g, and δ is the "th" in "this".',
          'Before e and i sounds, γ turns into a y: γεια is "ya".'
        ],
        te: 'Telugu has no letter for δ, so Mazí writes it as ద. Say it with the tongue touching the top teeth. ρ is exactly Telugu ర.',
        ex: [{ el: 'νερό', en: 'water' }, { el: 'δρόμος', en: 'road' }]
      },
      dialogue: {
        title: 'A glass of water', tip: 'Pass something to each other at dinner and use ευχαριστώ and παρακαλώ.',
        lines: [['A', 'Νερό;', 'Water?'], ['B', 'Ευχαριστώ!', 'Thank you!'], ['A', 'Παρακαλώ.', 'You\'re welcome.']]
      }
    },
    {
      n: 4, title: 'New shapes', goal: 'Read θ φ χ ψ ξ ζ, and say yes or no.',
      items: [
        { k: 'letter', up: 'Θ', el: 'θ', say: 'th', te: 'థ', en: 'th as in "think"' },
        { k: 'letter', up: 'Φ', el: 'φ', say: 'f', te: 'ఫ', en: 'a real f, as in "fan"' },
        { k: 'letter', up: 'Χ', el: 'χ', say: 'kh', te: 'ఖ', en: 'a throaty h, like "loch"' },
        { k: 'letter', up: 'Ψ', el: 'ψ', say: 'ps', te: 'ప్స', en: 'ps in one letter' },
        { k: 'letter', up: 'Ξ', el: 'ξ', say: 'ks', te: 'క్స', en: 'ks in one letter' },
        { k: 'letter', up: 'Ζ', el: 'ζ', say: 'z', te: 'జ', en: 'z as in "zoo"' },
        { el: 'Θεός', en: 'God', tm: 'దేవుడు' },
        { el: 'ψωμί', en: 'bread', tm: 'రొట్టె' },
        { el: 'ζωή', en: 'life', tm: 'జీవితం' },
        { el: 'Ναι / Όχι', en: 'Yes / No', tm: 'అవును / కాదు', note: 'Careful: ναι sounds like "ne" but means yes.' }
      ],
      grammar: {
        title: 'One letter, two English letters',
        body: [
          'Greek has single letters for sounds English spells with two: θ (th), φ (f), χ (kh), ψ (ps), ξ (ks).',
          'ψ is said as ps even at the start of a word: ψωμί is pso-MÍ.'
        ],
        te: 'θ is not quite థ: put your tongue between your teeth and let air flow, with no puff. φ is a real f, lips on teeth. ζ is the Hindi ज़, not Telugu జ.',
        ex: [{ el: 'Θεός', en: 'God' }, { el: 'ψωμί', en: 'bread' }]
      },
      dialogue: {
        title: 'Yes or no', tip: 'Offer each other three things at the table. Answer only ναι or όχι.',
        lines: [['A', 'Ψωμί;', 'Bread?'], ['B', 'Ναι, ευχαριστώ.', 'Yes, thank you.'], ['A', 'Γάλα;', 'Milk?'], ['B', 'Όχι, ευχαριστώ.', 'No, thank you.']]
      }
    },
    {
      n: 5, title: 'The loud syllable', goal: 'Use the accent mark, and say "I love you".',
      items: [
        { el: 'πότε', en: 'when', tm: 'ఎప్పుడు' },
        { el: 'ποτέ', en: 'never', tm: 'ఎన్నడూ' },
        { el: 'τι', en: 'what', tm: 'ఏమిటి' },
        { el: 'Σ\' αγαπώ', en: 'I love you', tm: 'నిన్ను ప్రేమిస్తున్నాను', note: 'αγαπώ is the verb behind αγάπη, the love of 1 Corinthians 13.' },
        { el: 'Κι εγώ', en: 'Me too', tm: 'నేను కూడా' }
      ],
      grammar: {
        title: 'Stress changes the word',
        body: [
          'Every Greek word of two or more syllables has one accent mark. Say that syllable louder.',
          'Moving the stress can change the meaning: πότε (PÓ-te) is "when", but ποτέ (po-TÉ) is "never".',
          'The Greek question mark looks like a semicolon: Πότε; means "When?"'
        ],
        te: 'Telugu stress is gentle. Greek stress is strong. In Mazí\'s Telugu script, a long vowel (ా ీ ూ ే ో) marks the loud syllable.',
        ex: [{ el: 'Πότε;', en: 'When?' }, { el: 'Ποτέ!', en: 'Never!' }]
      },
      dialogue: {
        title: 'Three little words', tip: 'Say this before you sleep tonight.',
        lines: [['A', 'Σ\' αγαπώ.', 'I love you.'], ['B', 'Κι εγώ σ\' αγαπώ.', 'I love you too.']]
      }
    },
    {
      n: 6, title: 'Two letters, one sound', goal: 'Read ου ει οι αι, and ask how someone is.',
      items: [
        { k: 'letter', up: 'ΟΥ', el: 'ου', say: 'u', te: 'ఉ', en: 'u as in "put"' },
        { k: 'letter', up: 'ΕΙ', el: 'ει', say: 'i', te: 'ఇ', en: 'i' },
        { k: 'letter', up: 'ΟΙ', el: 'οι', say: 'i', te: 'ఇ', en: 'i' },
        { k: 'letter', up: 'ΑΙ', el: 'αι', say: 'e', te: 'ఎ', en: 'e' },
        { el: 'ουρανός', en: 'sky, heaven', tm: 'ఆకాశం, పరలోకం' },
        { el: 'και', en: 'and', tm: 'మరియు' },
        { el: 'Τι κάνεις;', en: 'How are you?', tm: 'ఎలా ఉన్నావు?' },
        { el: 'Καλά, εσύ;', en: 'Good, and you?', tm: 'బాగున్నాను, నువ్వు?' }
      ],
      grammar: {
        title: 'Letter pairs',
        body: [
          'Four vowel pairs make a single sound: ου = u, ει = i, οι = i, αι = e.',
          'If the accent sits on the first letter, the pair splits into two sounds: τσάι (tea) is TSÁ-i.'
        ],
        te: 'So Greek now has five ways to write the ఇ sound: ι, η, υ, ει, οι.',
        ex: [{ el: 'ουρανός', en: 'heaven' }, { el: 'Τι κάνεις;', en: 'How are you?' }]
      },
      dialogue: {
        title: 'How are you?', tip: 'Ask this every evening this week.',
        lines: [['A', 'Γεια σου! Τι κάνεις;', 'Hi! How are you?'], ['B', 'Καλά, εσύ;', 'Good, and you?'], ['A', 'Καλά, ευχαριστώ.', 'Good, thank you.']]
      }
    },
    {
      n: 7, title: 'v or f: αυ and ευ', goal: 'Read αυ and ευ, and say sorry.',
      items: [
        { k: 'letter', up: 'ΑΥ', el: 'αυ', say: 'av / af', te: 'అవ్ / అఫ్', en: 'av, or af before hard sounds' },
        { k: 'letter', up: 'ΕΥ', el: 'ευ', say: 'ev / ef', te: 'ఎవ్ / ఎఫ్', en: 'ev, or ef before hard sounds' },
        { el: 'αύριο', en: 'tomorrow', tm: 'రేపు' },
        { el: 'αυτό', en: 'this, it', tm: 'ఇది' },
        { el: 'Ευαγγέλιο', en: 'Gospel', tm: 'సువార్త' },
        { el: 'Συγγνώμη', en: 'Sorry', tm: 'క్షమించు' },
        { el: 'Δεν πειράζει', en: 'No problem, it\'s fine', tm: 'పర్వాలేదు' },
        { el: 'Τα λέμε αύριο', en: 'See you tomorrow', tm: 'రేపు కలుద్దాం' }
      ],
      grammar: {
        title: 'When υ becomes v or f',
        body: [
          'After α or ε, the letter υ sounds like v: αύριο (ÁV-ri-o), Ευαγγέλιο (ev-an-GÉ-li-o).',
          'Before a hard sound (κ π τ θ φ χ σ ξ ψ) it becomes f: αυτό (af-TÓ), ευχαριστώ (ef-kha-ri-STÓ).'
        ],
        te: 'You already say ευχαριστώ with f. Now you know why.',
        ex: [{ el: 'αύριο', en: 'tomorrow' }, { el: 'αυτό', en: 'this' }]
      },
      dialogue: {
        title: 'Oops', tip: 'Bump into each other on purpose, then say it.',
        lines: [['A', 'Συγγνώμη!', 'Sorry!'], ['B', 'Δεν πειράζει.', 'No problem.'], ['A', 'Τα λέμε αύριο!', 'See you tomorrow!'], ['B', 'Τα λέμε!', 'See you!']]
      }
    },
    {
      n: 8, title: 'b, d and g', goal: 'Read μπ ντ γκ γγ τσ τζ.',
      items: [
        { k: 'letter', up: 'ΜΠ', el: 'μπ', say: 'b', te: 'బ', en: 'b' },
        { k: 'letter', up: 'ΝΤ', el: 'ντ', say: 'd', te: 'డ', en: 'd' },
        { k: 'letter', up: 'ΓΚ', el: 'γκ', say: 'g', te: 'గ', en: 'g as in "go"' },
        { k: 'letter', up: 'ΓΓ', el: 'γγ', say: 'ng', te: 'ంగ', en: 'ng as in "finger"' },
        { k: 'letter', up: 'ΤΣ', el: 'τσ', say: 'ts', te: 'త్స', en: 'ts' },
        { k: 'letter', up: 'ΤΖ', el: 'τζ', say: 'dz', te: 'ద్జ', en: 'dz' },
        { el: 'μπαμπάς', en: 'dad', tm: 'నాన్న' },
        { el: 'μαμά', en: 'mum', tm: 'అమ్మ' },
        { el: 'τσάι', en: 'tea', tm: 'టీ' },
        { el: 'άγγελος', en: 'angel', tm: 'దేవదూత' },
        { el: 'Πάμε!', en: 'Let\'s go!', tm: 'వెళ్దాం పద!' }
      ],
      grammar: {
        title: 'Borrowed sounds',
        body: [
          'Modern Greek has no single letter for b, d or g, so it uses pairs: μπ = b, ντ = d, γκ = g.',
          'γγ is ng, as in άγγελος (ÁN-ge-los). This is where the English word "angel" comes from.'
        ],
        te: 'The Greek d in ντ is soft, between Telugu ద and డ.',
        ex: [{ el: 'μπαμπάς', en: 'dad' }, { el: 'άγγελος', en: 'angel' }]
      },
      dialogue: {
        title: 'Tea time', tip: 'Make tea together and use Πάμε! to start.',
        lines: [['A', 'Τσάι;', 'Tea?'], ['B', 'Ναι! Πάμε!', 'Yes! Let\'s go!']]
      }
    },
    {
      n: 9, title: 'Greek you already know', goal: 'Read long words, and capital letters.',
      items: [
        { el: 'τηλέφωνο', en: 'telephone', tm: 'ఫోను' },
        { el: 'μουσική', en: 'music', tm: 'సంగీతం' },
        { el: 'θέατρο', en: 'theatre', tm: 'నాటకశాల' },
        { el: 'πρόβλημα', en: 'problem', tm: 'సమస్య' },
        { el: 'ιδέα', en: 'idea', tm: 'ఆలోచన' },
        { el: 'Δόξα τω Θεώ', en: 'Glory to God (thank God)', tm: 'దేవునికి మహిమ', note: 'Greeks say this every day, like "thank God". τω Θεώ is an old form straight from the Bible.' }
      ],
      grammar: {
        title: 'Capital letters',
        body: [
          'Capitals are the same letters, just bigger: Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω.',
          'Signs and headings are often written all in capitals, without accent marks: ΑΘΗΝΑ is Αθήνα (Athens).'
        ],
        te: 'English took thousands of words from Greek: telephone, music, theatre, problem, idea. You already know them.',
        ex: [{ el: 'ΘΕΑΤΡΟ', en: 'THEATRE' }, { el: 'Δόξα τω Θεώ!', en: 'Thank God!' }]
      },
      dialogue: {
        title: 'Thank God', tip: 'Use δόξα τω Θεώ whenever something good happens today.',
        lines: [['A', 'Τι κάνεις;', 'How are you?'], ['B', 'Καλά, δόξα τω Θεώ! Εσύ;', 'Good, thank God! You?'], ['A', 'Καλά, ευχαριστώ.', 'Good, thank you.']]
      }
    },
    {
      n: 10, title: 'Checkpoint: read it all', goal: 'Read any Greek word aloud.',
      items: [
        { el: 'Ελλάδα', en: 'Greece', tm: 'గ్రీసు' },
        { el: 'Ιησούς', en: 'Jesus', tm: 'యేసు' },
        { el: 'Χριστός', en: 'Christ', tm: 'క్రీస్తు' },
        { el: 'Βίβλος', en: 'Bible', tm: 'బైబిల్' },
        { el: 'Αγάπη μου', en: 'My love', tm: 'నా ప్రేమా' },
        { el: 'Καληνύχτα', en: 'Good night', tm: 'శుభ రాత్రి' },
        { el: 'Ο Θεός μαζί σου', en: 'God be with you', tm: 'దేవుడు నీకు తోడై ఉండును గాక' }
      ],
      grammar: {
        title: 'What you can do now',
        body: [
          'You know every Greek letter and every letter pair. You can read any Greek word aloud, even ones you don\'t understand yet.',
          'From the next lesson, you start building real sentences.'
        ],
        te: 'Try reading a Greek sign or a Greek Bible verse aloud. You will be surprised.',
        ex: [{ el: 'Ιησούς Χριστός', en: 'Jesus Christ' }]
      },
      dialogue: {
        title: 'Good night', tip: 'Make this your good-night routine from now on.',
        lines: [['A', 'Καληνύχτα, αγάπη μου.', 'Good night, my love.'], ['B', 'Καληνύχτα. Ο Θεός μαζί σου.', 'Good night. God be with you.'], ['A', 'Αμήν.', 'Amen.']]
      }
    },

    /* ---------------- Unit: You and me ---------------- */
    {
      n: 11, title: 'I am, you are', goal: 'Say who you are and ask a name.',
      items: [
        { el: 'εγώ', en: 'I', tm: 'నేను' },
        { el: 'εσύ', en: 'you', tm: 'నువ్వు' },
        { el: 'είμαι', en: 'I am', tm: '(నేను) ఉన్నాను' },
        { el: 'είσαι', en: 'you are', tm: '(నువ్వు) ఉన్నావు' },
        { el: 'Με λένε…', en: 'My name is…', tm: 'నా పేరు…' },
        { el: 'Πώς σε λένε;', en: 'What\'s your name?', tm: 'నీ పేరేమిటి?' },
        { el: 'Χαίρω πολύ', en: 'Nice to meet you', tm: 'మిమ్మల్ని కలవడం సంతోషం' }
      ],
      grammar: {
        title: 'Dropping "I" and "you"',
        body: [
          'είμαι already means "I am" and είσαι already means "you are". Greek usually leaves out εγώ and εσύ.',
          'Use εγώ or εσύ only for emphasis: Εγώ είμαι καλά. Εσύ; ("I am fine. And you?")'
        ],
        te: 'Telugu does the same: ఉన్నాను already means "I am", so నేను is optional.',
        ex: [{ el: 'Είμαι καλά.', en: 'I am fine.' }, { el: 'Είσαι καλά;', en: 'Are you fine?' }]
      },
      dialogue: {
        title: 'Strangers again', tip: 'Pretend you are meeting for the first time. Use your real names.',
        lines: [['A', 'Γεια σου! Με λένε ___. Πώς σε λένε;', 'Hi! My name is ___. What\'s your name?'], ['B', 'Με λένε ___.', 'My name is ___.'], ['A', 'Χαίρω πολύ!', 'Nice to meet you!'], ['B', 'Κι εγώ!', 'Me too!']]
      }
    },
    {
      n: 12, title: 'He, she and "the"', goal: 'Introduce your husband or wife.',
      items: [
        { el: 'αυτός', en: 'he', tm: 'అతను' },
        { el: 'αυτή', en: 'she', tm: 'ఆమె' },
        { el: 'είναι', en: 'he / she / it is', tm: 'ఉన్నాడు / ఉంది' },
        { el: 'ο άντρας μου', en: 'my husband', tm: 'నా భర్త', note: 'άντρας means both "man" and "husband".' },
        { el: 'η γυναίκα μου', en: 'my wife', tm: 'నా భార్య', note: 'γυναίκα means both "woman" and "wife".' },
        { el: 'ο / η', en: 'the (for him / for her)', tm: 'పురుష / స్త్రీ పదాల ముందు "the"' }
      ],
      grammar: {
        title: 'ο for him, η for her',
        body: [
          '"The" changes with the word: ο for masculine words (ο άντρας), η for feminine words (η γυναίκα).',
          'μου after a word means "my": ο άντρας μου, η γυναίκα μου.'
        ],
        te: 'Telugu shows he or she in the verb (వచ్చాడు / వచ్చింది). Greek shows it in "the": ο / η.',
        ex: [{ el: 'Αυτή είναι η γυναίκα μου.', en: 'This is my wife.' }, { el: 'Αυτός είναι ο άντρας μου.', en: 'This is my husband.' }]
      },
      dialogue: {
        title: 'Meet my spouse', tip: 'Introduce each other to an imaginary guest (a chair works).',
        lines: [['A', 'Αυτή είναι η γυναίκα μου.', 'This is my wife.'], ['B', 'Και αυτός είναι ο άντρας μου.', 'And this is my husband.'], ['A', 'Χαίρω πολύ!', 'Nice to meet you!']]
      }
    },
    {
      n: 13, title: 'How do you feel?', goal: 'Say how you feel, as a man or as a woman.',
      items: [
        { el: 'Πώς είσαι;', en: 'How are you (feeling)?', tm: 'ఎలా ఉన్నావు?' },
        { el: 'χαρούμενος / χαρούμενη', en: 'happy (him / her)', tm: 'సంతోషంగా' },
        { el: 'κουρασμένος / κουρασμένη', en: 'tired (him / her)', tm: 'అలసిపోయి' },
        { el: 'λυπημένος / λυπημένη', en: 'sad (him / her)', tm: 'బాధగా' },
        { el: 'ήρεμος / ήρεμη', en: 'calm (him / her)', tm: 'ప్రశాంతంగా' },
        { el: 'άρρωστος / άρρωστη', en: 'sick (him / her)', tm: 'జబ్బుగా' }
      ],
      grammar: {
        title: '-ος for him, -η for her',
        body: [
          'Describing words change with who they describe. A man says Είμαι κουρασμένος. A woman says Είμαι κουρασμένη.',
          'In the lists, the first form is for him and the second for her.'
        ],
        te: 'Just like Telugu అలసిపోయాడు / అలసిపోయింది, the ending shows man or woman.',
        ex: [{ el: 'Είμαι χαρούμενος.', en: 'I am happy (man).' }, { el: 'Είμαι χαρούμενη.', en: 'I am happy (woman).' }]
      },
      dialogue: {
        title: 'Checking in', tip: 'Use your own form: -ος for him, -η for her.',
        lines: [['A', 'Πώς είσαι;', 'How are you?'], ['B', 'Είμαι κουρασμένος / κουρασμένη. Εσύ;', 'I\'m tired. You?'], ['A', 'Είμαι χαρούμενος / χαρούμενη!', 'I\'m happy!']]
      }
    },
    {
      n: 14, title: 'Question words', goal: 'Ask what, where, how, who and why.',
      items: [
        { el: 'πού', en: 'where', tm: 'ఎక్కడ' },
        { el: 'πώς', en: 'how', tm: 'ఎలా' },
        { el: 'ποιος / ποια', en: 'who (him / her)', tm: 'ఎవరు' },
        { el: 'γιατί', en: 'why; because', tm: 'ఎందుకు; ఎందుకంటే' },
        { el: 'εδώ / εκεί', en: 'here / there', tm: 'ఇక్కడ / అక్కడ' },
        { el: 'Τι είναι αυτό;', en: 'What is this?', tm: 'ఇది ఏమిటి?' }
      ],
      grammar: {
        title: 'Asking questions',
        body: [
          'Question words go first: Πού είσαι; (Where are you?) Τι είναι αυτό; (What is this?)',
          'For yes/no questions, keep the normal sentence and raise your voice at the end: Είσαι καλά; (Are you OK?)',
          'Watch the accent: πού means "where", but που without an accent means "that / who" in the middle of a sentence.'
        ],
        te: 'Telugu adds -ఆ to make a question (బాగున్నావా?). Greek just raises the voice.',
        ex: [{ el: 'Πού είσαι;', en: 'Where are you?' }, { el: 'Γιατί;', en: 'Why?' }]
      },
      dialogue: {
        title: 'What is this?', tip: 'Point at things around you and ask Τι είναι αυτό; Answer with words you know.',
        lines: [['A', 'Τι είναι αυτό;', 'What is this?'], ['B', 'Είναι νερό.', 'It\'s water.'], ['A', 'Πού είναι το ψωμί;', 'Where is the bread?'], ['B', 'Εκεί!', 'There!']]
      }
    },
    {
      n: 15, title: 'Not, maybe, of course', goal: 'Say no politely and make negative sentences.',
      items: [
        { el: 'δεν', en: 'not', tm: 'కాదు / లేదు' },
        { el: 'ξέρω', en: 'I know', tm: 'నాకు తెలుసు' },
        { el: 'Δεν ξέρω', en: 'I don\'t know', tm: 'నాకు తెలియదు' },
        { el: 'ίσως', en: 'maybe', tm: 'బహుశా' },
        { el: 'βέβαια', en: 'of course', tm: 'తప్పకుండా' },
        { el: 'Εντάξει', en: 'OK', tm: 'సరే' }
      ],
      grammar: {
        title: 'δεν goes before the verb',
        body: [
          'To say "not", put δεν right before the verb: Είμαι κουρασμένος → Δεν είμαι κουρασμένος.',
          'Όχι answers a question ("No"). δεν makes a sentence negative.'
        ],
        te: 'Telugu puts "not" at the end (తెలియదు). Greek puts δεν at the front of the verb.',
        ex: [{ el: 'Δεν ξέρω.', en: 'I don\'t know.' }, { el: 'Δεν είμαι κουρασμένη.', en: 'I\'m not tired (woman).' }]
      },
      dialogue: {
        title: 'Not tired', tip: 'Ask each other three yes/no questions. Answer with δεν.',
        lines: [['A', 'Είσαι κουρασμένη;', 'Are you tired?'], ['B', 'Όχι, δεν είμαι κουρασμένη. Εσύ;', 'No, I\'m not tired. You?'], ['A', 'Δεν ξέρω… ίσως!', 'I don\'t know… maybe!'], ['B', 'Εντάξει.', 'OK.']]
      }
    },
    {
      n: 16, title: 'We are together', goal: 'Use we, you (plural) and they.',
      items: [
        { el: 'εμείς', en: 'we', tm: 'మేము / మనం' },
        { el: 'εσείς', en: 'you (plural, or polite)', tm: 'మీరు' },
        { el: 'αυτοί', en: 'they', tm: 'వారు' },
        { el: 'είμαστε', en: 'we are', tm: '(మనం) ఉన్నాం' },
        { el: 'είστε', en: 'you are (plural)', tm: '(మీరు) ఉన్నారు' },
        { el: 'μαζί', en: 'together', tm: 'కలిసి', note: 'This is the name of the app.' }
      ],
      grammar: {
        title: 'The whole verb "to be"',
        body: [
          'εγώ είμαι · εσύ είσαι · αυτός / αυτή είναι',
          'εμείς είμαστε · εσείς είστε · αυτοί είναι',
          'είναι means both "he/she is" and "they are".'
        ],
        te: 'εσείς is also the polite "you" for elders, like Telugu మీరు.',
        ex: [{ el: 'Είμαστε μαζί.', en: 'We are together.' }, { el: 'Πού είστε;', en: 'Where are you (all)?' }]
      },
      dialogue: {
        title: 'Together', tip: 'Hold hands for this one.',
        lines: [['A', 'Είμαστε μαζί.', 'We are together.'], ['B', 'Ναι, είμαστε μαζί. Δόξα τω Θεώ!', 'Yes, we are together. Thank God!']]
      }
    },
    {
      n: 17, title: 'Numbers 1 to 5', goal: 'Count to five and ask how many.',
      items: [
        { el: 'ένα', en: 'one', tm: 'ఒకటి' },
        { el: 'δύο', en: 'two', tm: 'రెండు' },
        { el: 'τρία', en: 'three', tm: 'మూడు' },
        { el: 'τέσσερα', en: 'four', tm: 'నాలుగు' },
        { el: 'πέντε', en: 'five', tm: 'ఐదు' },
        { el: 'Πόσα;', en: 'How many?', tm: 'ఎన్ని?' }
      ],
      grammar: {
        title: 'Cousins of Sanskrit',
        body: [
          'Greek and Sanskrit come from the same ancient family, and the numbers show it.',
          'δύο and ద్వి, τρία and త్రి, πέντε and పంచ.'
        ],
        te: 'You already know these roots from Telugu words like ద్వితీయ, త్రికోణం and పంచాంగం.',
        ex: [{ el: 'ένα, δύο, τρία', en: 'one, two, three' }]
      },
      dialogue: {
        title: 'How many?', tip: 'Count spoons, cups and fingers together.',
        lines: [['A', 'Πόσα;', 'How many?'], ['B', 'Τρία.', 'Three.'], ['A', 'Τρία; Όχι, τέσσερα!', 'Three? No, four!']]
      }
    },
    {
      n: 18, title: 'Numbers 6 to 10', goal: 'Count to ten and say the time.',
      items: [
        { el: 'έξι', en: 'six', tm: 'ఆరు' },
        { el: 'εφτά', en: 'seven', tm: 'ఏడు' },
        { el: 'οχτώ', en: 'eight', tm: 'ఎనిమిది' },
        { el: 'εννιά', en: 'nine', tm: 'తొమ్మిది' },
        { el: 'δέκα', en: 'ten', tm: 'పది' },
        { el: 'Τι ώρα είναι;', en: 'What time is it?', tm: 'టైం ఎంత అయింది?' }
      ],
      grammar: {
        title: 'Telling the hour',
        body: [
          'Say the hour with είναι: Είναι εφτά. (It\'s seven.)',
          'You will also see επτά, οκτώ and εννέα. These are the formal spellings of the same numbers.'
        ],
        te: 'More Sanskrit cousins: έξι and షట్, εφτά and సప్త, οχτώ and అష్ట, εννιά and నవ, δέκα and దశ.',
        ex: [{ el: 'Είναι δέκα.', en: 'It\'s ten o\'clock.' }]
      },
      dialogue: {
        title: 'Time to go', tip: 'Ask the time three times today.',
        lines: [['A', 'Τι ώρα είναι;', 'What time is it?'], ['B', 'Είναι εφτά.', 'It\'s seven.'], ['A', 'Εφτά; Πάμε!', 'Seven? Let\'s go!']]
      }
    },
    {
      n: 19, title: 'Words of love', goal: 'Say sweet things to each other.',
      items: [
        { el: 'καρδιά μου', en: 'my heart (sweetheart)', tm: 'నా ప్రాణమా' },
        { el: 'μωρό μου', en: 'my baby', tm: 'నా బంగారం' },
        { el: 'Μου λείπεις', en: 'I miss you', tm: 'నువ్వు గుర్తొస్తున్నావు' },
        { el: 'Είσαι όμορφη / όμορφος', en: 'You are beautiful (to her / to him)', tm: 'నువ్వు అందంగా ఉన్నావు' },
        { el: 'Είμαι τυχερός / τυχερή', en: 'I am lucky (man / woman)', tm: 'నేను అదృష్టవంతుడిని / అదృష్టవంతురాలిని' },
        { el: 'Φιλάκια', en: 'Kisses (to sign off)', tm: 'ముద్దులు' }
      ],
      grammar: {
        title: 'μου means "my" and "to me"',
        body: [
          'After a word, μου means "my": η καρδιά μου (my heart), το μωρό μου (my baby).',
          'Before a verb, μου means "to me": Μου λείπεις is literally "You are missing to me".'
        ],
        te: 'Just like Telugu నాకు గుర్తొస్తున్నావు, "to me" comes first.',
        ex: [{ el: 'Μου λείπεις, καρδιά μου.', en: 'I miss you, sweetheart.' }]
      },
      dialogue: {
        title: 'Missing you', tip: 'Send one of these lines on WhatsApp today, in Greek.',
        lines: [['A', 'Μου λείπεις, καρδιά μου.', 'I miss you, sweetheart.'], ['B', 'Κι εσύ μου λείπεις.', 'I miss you too.'], ['A', 'Σ\' αγαπώ.', 'I love you.'], ['B', 'Κι εγώ σ\' αγαπώ. Φιλάκια!', 'I love you too. Kisses!']]
      }
    },
    {
      n: 20, title: 'Checkpoint: breakfast talk', goal: 'Have a whole breakfast conversation in Greek.',
      items: [
        { el: 'Κοιμήθηκες καλά;', en: 'Did you sleep well?', tm: 'బాగా నిద్రపోయావా?' },
        { el: 'πολύ', en: 'very, a lot', tm: 'చాలా' },
        { el: 'Ναι, πολύ καλά', en: 'Yes, very well', tm: 'అవును, చాలా బాగా' },
        { el: 'Καλή όρεξη', en: 'Enjoy your meal', tm: 'హాయిగా తినండి' }
      ],
      grammar: {
        title: 'What you can do now',
        body: [
          'You can greet, introduce each other, say how you feel, ask questions, say no, count to ten, tell the hour and say sweet things.',
          'Read the whole dialogue below twice, swapping roles the second time.'
        ],
        te: 'This is real Greek. Greek couples say exactly these things every morning.',
        ex: [{ el: 'Κοιμήθηκες καλά;', en: 'Did you sleep well?' }]
      },
      dialogue: {
        title: 'Breakfast', tip: 'Do it at the real breakfast table tomorrow.',
        lines: [
          ['A', 'Καλημέρα, αγάπη μου!', 'Good morning, my love!'],
          ['B', 'Καλημέρα!', 'Good morning!'],
          ['A', 'Κοιμήθηκες καλά;', 'Did you sleep well?'],
          ['B', 'Ναι, πολύ καλά. Εσύ;', 'Yes, very well. You?'],
          ['A', 'Όχι πολύ. Είμαι κουρασμένος / κουρασμένη.', 'Not really. I\'m tired.'],
          ['B', 'Τσάι;', 'Tea?'],
          ['A', 'Ναι, ευχαριστώ!', 'Yes, thank you!'],
          ['B', 'Παρακαλώ. Καλή όρεξη!', 'You\'re welcome. Enjoy!']
        ]
      }
    },

    /* ---------------- Unit: Home and food ---------------- */
    {
      n: 21, title: 'I have', goal: 'Say what you have and ask if someone has time.',
      items: [
        { el: 'έχω', en: 'I have', tm: 'నా దగ్గర ఉంది' },
        { el: 'έχεις', en: 'you have', tm: 'నీ దగ్గర ఉంది' },
        { el: 'έχει', en: 'he / she has', tm: 'అతని / ఆమె దగ్గర ఉంది' },
        { el: 'σπίτι', en: 'house, home', tm: 'ఇల్లు' },
        { el: 'χρόνο', en: 'time (to spare)', tm: 'సమయం' },
        { el: 'Έχεις χρόνο;', en: 'Do you have time?', tm: 'నీకు సమయం ఉందా?' }
      ],
      grammar: {
        title: 'Verbs that end in -ω',
        body: [
          'Most Greek verbs end in -ω, and the ending tells you who: έχω (I have), έχεις (you have), έχει (he/she has).',
          'Plural: έχουμε (we have), έχετε (you have), έχουν (they have).'
        ],
        te: 'Telugu says నా దగ్గర ఉంది, "with me there is". Greek simply says έχω, "I have".',
        ex: [{ el: 'Δεν έχω χρόνο.', en: 'I don\'t have time.' }]
      },
      dialogue: {
        title: 'Coffee date', tip: 'Actually go for coffee this week, and ask in Greek.',
        lines: [['A', 'Έχεις χρόνο;', 'Do you have time?'], ['B', 'Ναι, έχω.', 'Yes, I do.'], ['A', 'Πάμε για καφέ;', 'Shall we go for coffee?'], ['B', 'Πάμε!', 'Let\'s go!']]
      }
    },
    {
      n: 22, title: 'The: ο, η, το', goal: 'Name things at home with the right "the".',
      items: [
        { el: 'ο καφές', en: 'the coffee', tm: 'కాఫీ' },
        { el: 'η πόρτα', en: 'the door', tm: 'తలుపు' },
        { el: 'το νερό', en: 'the water', tm: 'నీళ్ళు' },
        { el: 'η κουζίνα', en: 'the kitchen', tm: 'వంటగది' },
        { el: 'το παράθυρο', en: 'the window', tm: 'కిటికీ' },
        { el: 'το σπίτι', en: 'the house', tm: 'ఇల్లు' }
      ],
      grammar: {
        title: 'Three genders',
        body: [
          'Every Greek noun is masculine (ο), feminine (η) or neuter (το), even things.',
          'The ending usually tells you: -ος, -ας, -ης → ο · -α, -η → η · -ο, -ι, -μα → το.',
          'Always learn a new word together with its ο, η or το.'
        ],
        te: 'Telugu calls things అది (neuter). Greek gives every noun a gender, like Hindi does.',
        ex: [{ el: 'Πού είναι το νερό;', en: 'Where is the water?' }, { el: 'Η πόρτα είναι εκεί.', en: 'The door is there.' }]
      },
      dialogue: {
        title: 'Where is it?', tip: 'Walk around the house and ask about each thing.',
        lines: [['A', 'Πού είναι ο καφές;', 'Where is the coffee?'], ['B', 'Εκεί, στην κουζίνα.', 'There, in the kitchen.'], ['A', 'Ευχαριστώ!', 'Thanks!']]
      }
    },
    {
      n: 23, title: 'I want', goal: 'Say what you want, and offer drinks.',
      items: [
        { el: 'θέλω', en: 'I want', tm: 'నాకు కావాలి' },
        { el: 'θέλεις', en: 'you want', tm: 'నీకు కావాలా' },
        { el: 'Θέλεις καφέ ή τσάι;', en: 'Do you want coffee or tea?', tm: 'కాఫీ కావాలా, టీ కావాలా?' },
        { el: 'λίγο', en: 'a little', tm: 'కొంచెం' },
        { el: 'ζάχαρη', en: 'sugar', tm: 'చక్కెర' },
        { el: 'Δεν θέλω', en: 'I don\'t want', tm: 'నాకు వద్దు' }
      ],
      grammar: {
        title: 'The "object" form',
        body: [
          'When a masculine word is the thing you want, its final ς drops: ο καφές → Θέλω καφέ.',
          'Feminine and neuter words stay the same: Θέλω ζάχαρη. Θέλω νερό.',
          'ή (with an accent) means "or".'
        ],
        te: 'Like Telugu adding -ని to the object (కాఫీని), Greek changes the ending of the thing.',
        ex: [{ el: 'Θέλω καφέ.', en: 'I want coffee.' }, { el: 'Θέλεις ζάχαρη;', en: 'Do you want sugar?' }]
      },
      dialogue: {
        title: 'Coffee or tea?', tip: 'Make each other a drink tonight, asking only in Greek.',
        lines: [['A', 'Θέλεις καφέ ή τσάι;', 'Coffee or tea?'], ['B', 'Καφέ, παρακαλώ.', 'Coffee, please.'], ['A', 'Ζάχαρη;', 'Sugar?'], ['B', 'Λίγο.', 'A little.']]
      }
    },
    {
      n: 24, title: 'Food', goal: 'Name everyday foods and decide what to eat.',
      items: [
        { el: 'ρύζι', en: 'rice', tm: 'అన్నం / బియ్యం' },
        { el: 'κοτόπουλο', en: 'chicken', tm: 'చికెన్' },
        { el: 'αυγό / αυγά', en: 'egg / eggs', tm: 'గుడ్డు / గుడ్లు' },
        { el: 'ψάρι', en: 'fish', tm: 'చేప' },
        { el: 'λαχανικά', en: 'vegetables', tm: 'కూరగాయలు' },
        { el: 'φρούτα', en: 'fruit', tm: 'పండ్లు' },
        { el: 'Τι θέλεις να φάμε;', en: 'What shall we eat?', tm: 'ఏం తిందాం?' }
      ],
      grammar: {
        title: 'Plurals of το-words',
        body: [
          'Neuter words ending in -ο change to -α: το αυγό → τα αυγά.',
          'Words ending in -ι add -α: το ψάρι → τα ψάρια.',
          'The plural of το is τα.'
        ],
        te: 'Telugu adds -లు (గుడ్లు). Greek changes the ending instead.',
        ex: [{ el: 'Θέλω δύο αυγά.', en: 'I want two eggs.' }]
      },
      dialogue: {
        title: 'Dinner plans', tip: 'Decide tomorrow\'s dinner in Greek.',
        lines: [['A', 'Τι θέλεις να φάμε;', 'What shall we eat?'], ['B', 'Ρύζι και κοτόπουλο.', 'Rice and chicken.'], ['A', 'Και λαχανικά;', 'And vegetables?'], ['B', 'Ναι, βέβαια!', 'Yes, of course!']]
      }
    },
    {
      n: 25, title: 'At the table', goal: 'Talk at the dinner table.',
      items: [
        { el: 'Πεινάω', en: 'I\'m hungry', tm: 'నాకు ఆకలిగా ఉంది' },
        { el: 'Διψάω', en: 'I\'m thirsty', tm: 'నాకు దాహంగా ఉంది' },
        { el: 'Το φαγητό είναι έτοιμο', en: 'The food is ready', tm: 'భోజనం సిద్ధంగా ఉంది' },
        { el: 'Πολύ νόστιμο!', en: 'Very tasty!', tm: 'చాలా రుచిగా ఉంది!' },
        { el: 'Κι άλλο;', en: 'More?', tm: 'ఇంకా కావాలా?' },
        { el: 'Χόρτασα', en: 'I\'m full', tm: 'కడుపు నిండింది' }
      ],
      grammar: {
        title: 'Verbs that end in -άω',
        body: [
          'Some verbs end in -άω: πεινάω (I\'m hungry), διψάω (I\'m thirsty), αγαπάω (I love).',
          'They go: πεινάω, πεινάς, πεινάει, πεινάμε, πεινάτε, πεινάνε.'
        ],
        te: 'Greek says "I hunger" with one verb, where Telugu says నాకు ఆకలిగా ఉంది.',
        ex: [{ el: 'Πεινάς;', en: 'Are you hungry?' }]
      },
      dialogue: {
        title: 'Dinner is ready', tip: 'Use these at tonight\'s dinner.',
        lines: [['A', 'Πεινάω!', 'I\'m hungry!'], ['B', 'Το φαγητό είναι έτοιμο.', 'The food is ready.'], ['A', 'Πολύ νόστιμο!', 'Very tasty!'], ['B', 'Κι άλλο;', 'More?'], ['A', 'Όχι, ευχαριστώ. Χόρτασα.', 'No, thanks. I\'m full.']]
      }
    },
    {
      n: 26, title: 'Where in the house?', goal: 'Say where you are at home.',
      items: [
        { el: 'το σαλόνι', en: 'the living room', tm: 'హాలు' },
        { el: 'η κρεβατοκάμαρα', en: 'the bedroom', tm: 'పడకగది' },
        { el: 'το μπάνιο', en: 'the bathroom', tm: 'స్నానాల గది' },
        { el: 'ο κήπος', en: 'the garden', tm: 'తోట' },
        { el: 'στο / στην', en: 'in the, at the', tm: '…లో' },
        { el: 'Έλα εδώ!', en: 'Come here!', tm: 'ఇక్కడికి రా!' }
      ],
      grammar: {
        title: 'σε + the = στο, στην',
        body: [
          'σε means "in / at / to". It joins with "the": σε + το = στο, σε + την = στην, σε + τον = στον.',
          'Είμαι στο σαλόνι. (I\'m in the living room.) Είμαι στην κουζίνα. (I\'m in the kitchen.)'
        ],
        te: 'Like Telugu -లో: వంటగదిలో = στην κουζίνα.',
        ex: [{ el: 'Είμαι στον κήπο.', en: 'I\'m in the garden.' }]
      },
      dialogue: {
        title: 'Where are you?', tip: 'Call each other from different rooms, in Greek only.',
        lines: [['A', 'Πού είσαι;', 'Where are you?'], ['B', 'Στην κουζίνα. Εσύ;', 'In the kitchen. You?'], ['A', 'Στο σαλόνι. Έλα εδώ!', 'In the living room. Come here!']]
      }
    },
    {
      n: 27, title: 'Things at home', goal: 'Find things around the house.',
      items: [
        { el: 'το τραπέζι', en: 'the table', tm: 'బల్ల' },
        { el: 'η καρέκλα', en: 'the chair', tm: 'కుర్చీ' },
        { el: 'το κρεβάτι', en: 'the bed', tm: 'మంచం' },
        { el: 'τα κλειδιά', en: 'the keys', tm: 'తాళాలు' },
        { el: 'το τηλέφωνο', en: 'the phone', tm: 'ఫోను' },
        { el: 'η τσάντα', en: 'the bag', tm: 'సంచి' }
      ],
      grammar: {
        title: 'Plurals of η-words',
        body: [
          'Feminine words ending in -α or -η change to -ες: η καρέκλα → οι καρέκλες.',
          'The plural of ο and η is οι: οι καρέκλες. The plural of το is τα: τα κλειδιά.'
        ],
        te: 'Greek has two plural "the" words: οι (for ο and η words) and τα (for το words).',
        ex: [{ el: 'Πού είναι τα κλειδιά;', en: 'Where are the keys?' }]
      },
      dialogue: {
        title: 'Lost keys', tip: 'Hide the keys and ask for them in Greek.',
        lines: [['A', 'Πού είναι τα κλειδιά;', 'Where are the keys?'], ['B', 'Στο τραπέζι.', 'On the table.'], ['A', 'Και το τηλέφωνό μου;', 'And my phone?'], ['B', 'Στην τσάντα σου!', 'In your bag!']]
      }
    },
    {
      n: 28, title: 'Big, small, hot, cold', goal: 'Describe things.',
      items: [
        { el: 'μεγάλος / μεγάλη / μεγάλο', en: 'big', tm: 'పెద్ద' },
        { el: 'μικρός / μικρή / μικρό', en: 'small', tm: 'చిన్న' },
        { el: 'ζεστός / ζεστή / ζεστό', en: 'hot', tm: 'వేడి' },
        { el: 'κρύος / κρύα / κρύο', en: 'cold', tm: 'చల్లని' },
        { el: 'καινούργιος / καινούργια / καινούργιο', en: 'new', tm: 'కొత్త' },
        { el: 'Ωραία!', en: 'Great! Lovely!', tm: 'బాగుంది!' }
      ],
      grammar: {
        title: 'Describing words match',
        body: [
          'A describing word takes the ending of its noun: ο μεγάλος κήπος, η μεγάλη κουζίνα, το μεγάλο σπίτι.',
          'Some feminine forms end in -α instead of -η: κρύα, καινούργια.'
        ],
        te: 'Telugu పెద్ద never changes. Greek μεγάλος changes to match ο, η or το.',
        ex: [{ el: 'Το τσάι είναι κρύο.', en: 'The tea is cold.' }]
      },
      dialogue: {
        title: 'Cold tea', tip: 'Describe three things on the table.',
        lines: [['A', 'Το τσάι είναι κρύο!', 'The tea is cold!'], ['B', 'Συγγνώμη! Θέλεις ζεστό τσάι;', 'Sorry! Do you want hot tea?'], ['A', 'Ναι, ευχαριστώ.', 'Yes, thank you.'], ['B', 'Ωραία!', 'Great!']]
      }
    },
    {
      n: 29, title: 'Cooking together', goal: 'Talk while you cook.',
      items: [
        { el: 'μαγειρεύω', en: 'I cook', tm: 'నేను వండుతాను' },
        { el: 'τρώω', en: 'I eat', tm: 'నేను తింటాను' },
        { el: 'πίνω', en: 'I drink', tm: 'నేను తాగుతాను' },
        { el: 'πλένω', en: 'I wash', tm: 'నేను కడుగుతాను' },
        { el: 'Να βοηθήσω;', en: 'Shall I help?', tm: 'సహాయం చేయనా?' },
        { el: 'Τι μαγειρεύεις;', en: 'What are you cooking?', tm: 'ఏం వండుతున్నావు?' }
      ],
      grammar: {
        title: 'The full present tense',
        body: [
          'μαγειρεύω (I cook) · μαγειρεύεις (you cook) · μαγειρεύει (he/she cooks)',
          'μαγειρεύουμε (we cook) · μαγειρεύετε (you cook) · μαγειρεύουν (they cook)',
          'The same endings work for most verbs: πλένω, πλένεις, πλένει…'
        ],
        te: 'Telugu verbs change by person too: వండుతాను, వండుతావు, వండుతాడు.',
        ex: [{ el: 'Μαγειρεύουμε μαζί.', en: 'We cook together.' }]
      },
      dialogue: {
        title: 'In the kitchen', tip: 'Cook one meal this week speaking only Greek.',
        lines: [['A', 'Τι μαγειρεύεις;', 'What are you cooking?'], ['B', 'Ρύζι και ψάρι.', 'Rice and fish.'], ['A', 'Να βοηθήσω;', 'Shall I help?'], ['B', 'Ναι! Πλένεις τα λαχανικά;', 'Yes! Will you wash the vegetables?'], ['A', 'Εντάξει.', 'OK.']]
      }
    },
    {
      n: 30, title: 'Checkpoint: dinner at home', goal: 'Have a full evening conversation.',
      items: [
        { el: 'Γύρισα!', en: 'I\'m home! (I\'m back)', tm: 'నేను వచ్చేశాను!' },
        { el: 'Καλώς ήρθες', en: 'Welcome (home)', tm: 'స్వాగతం' },
        { el: 'Πώς πήγε η μέρα σου;', en: 'How was your day?', tm: 'నీ రోజు ఎలా గడిచింది?' },
        { el: 'αλλά', en: 'but', tm: 'కానీ' },
        { el: 'Ας προσευχηθούμε', en: 'Let\'s pray', tm: 'ప్రార్థన చేద్దాం' }
      ],
      grammar: {
        title: 'What you can do now',
        body: [
          'You can talk about home, food, where things are and what you want, and describe things.',
          'That is enough Greek for a whole evening at home. Read the dialogue twice, swapping roles.'
        ],
        te: 'From here, the course moves on to your daily routine.',
        ex: [{ el: 'Πώς πήγε η μέρα σου;', en: 'How was your day?' }]
      },
      dialogue: {
        title: 'Evening at home', tip: 'Do this tonight when one of you comes home.',
        lines: [
          ['A', 'Γύρισα!', 'I\'m home!'],
          ['B', 'Καλώς ήρθες, αγάπη μου! Πώς πήγε η μέρα σου;', 'Welcome home, my love! How was your day?'],
          ['A', 'Καλά, αλλά είμαι κουρασμένος / κουρασμένη. Πεινάω!', 'Good, but I\'m tired. I\'m hungry!'],
          ['B', 'Το φαγητό είναι έτοιμο. Ρύζι και κοτόπουλο.', 'The food is ready. Rice and chicken.'],
          ['A', 'Ωραία! Ας προσευχηθούμε.', 'Lovely! Let\'s pray.'],
          ['B', 'Αμήν. Καλή όρεξη!', 'Amen. Enjoy your meal!']
        ]
      }
    }
  ]
};

// Per-lesson extras for the lesson page and practice:
// setting (scene line), turn (three "your turn" prompts for the couple), bible, know (did you know),
// drills (fill the gap: "___" marks the gap, a = answer, o = options), spot (one wrong word), table (grammar pattern).
window.MAZI_COURSE.extra = {
  1: {
    setting: 'Your first evening with Greek. Sit side by side.',
    turn: ['Say Γεια σου to each other three ways: happy, sleepy, surprised.', 'Point at a vowel on the screen and let your spouse say its sound.', 'Say the sounds together slowly: α, ε, ι, ο.'],
    know: 'Γεια comes from υγεία, "health". Every time you say Γεια σου, you wish someone good health.'
  },
  2: {
    setting: 'Morning. The first words of the day.',
    turn: ['Say Καλημέρα to each other tomorrow before anything else.', 'Read καλό and όνομα aloud, stressing the marked syllable.', 'Try writing your spouse\'s name with the Greek letters you know so far.'],
    bible: { ref: 'Philippians 2:9', koine: 'τὸ ὄνομα τὸ ὑπὲρ πᾶν ὄνομα', en: 'the name that is above every name', note: 'ὄνομα, "name", is the word you learned today.' },
    know: 'Greeks say Καλημέρα until about midday, and Καλησπέρα from the afternoon on.'
  },
  3: {
    setting: 'Dinner. One of you passes the water.',
    turn: ['At dinner, offer water, milk or bread in Greek, and answer with ευχαριστώ and παρακαλώ.', 'Say δρόμος three times, with your tongue touching your teeth for δ.', 'Say νερό, γάλα and δρόμος to each other and check the stress.'],
    bible: { ref: 'John 4:10', koine: 'ἔδωκεν ἄν σοι ὕδωρ ζῶν', en: 'he would have given you living water', note: 'The Bible word for water is ὕδωρ (as in "hydro"). Today Greeks say νερό.' },
    know: 'νερό comes from a Byzantine phrase for fresh water, νεαρόν ὕδωρ.'
  },
  4: {
    setting: 'Breakfast table.',
    turn: ['Offer each other three things at the table. Answer only ναι or όχι.', 'Say Θεός, ψωμί and ζωή to each other, then swap.', 'Say θ and δ one after the other until you can hear the difference.'],
    bible: { ref: 'John 6:35', koine: 'ἐγώ εἰμι ὁ ἄρτος τῆς ζωῆς', en: 'I am the bread of life', note: 'ζωή (life) is today\'s word. The Bible\'s bread is ἄρτος; today Greeks say ψωμί.' },
    know: 'Greeks often say "no" with a small upward nod and raised eyebrows. Don\'t mistake it for yes.'
  },
  5: {
    setting: 'Bedtime.',
    turn: ['Say Σ\' αγαπώ and answer Κι εγώ σ\' αγαπώ.', 'Ask Πότε; and answer Ποτέ!, with the stress in the right place.', 'Read three words from earlier lessons and clap on the stressed syllable.'],
    bible: { ref: '1 John 4:19', koine: 'ἡμεῖς ἀγαπῶμεν, ὅτι αὐτὸς πρῶτος ἠγάπησεν ἡμᾶς', en: 'We love, because he first loved us.', note: 'ἀγαπῶμεν and ἠγάπησεν are forms of αγαπώ, the verb in Σ\' αγαπώ.' }
  },
  6: {
    setting: 'Evening. One of you comes home.',
    turn: ['Ask Τι κάνεις; every evening this week.', 'Find ου, ει, οι and αι in this lesson\'s words and read them aloud.', 'Answer Τι κάνεις; with Καλά, εσύ; and keep going.'],
    bible: { ref: 'Matthew 6:9', koine: 'Πάτερ ἡμῶν ὁ ἐν τοῖς οὐρανοῖς', en: 'Our Father in heaven', note: 'οὐρανοῖς is today\'s word ουρανός, "heaven".' }
  },
  7: {
    setting: 'You bump into each other in the kitchen.',
    turn: ['Say Συγγνώμη and answer Δεν πειράζει.', 'End today with Τα λέμε αύριο!', 'Sort these into v and f: αύριο, αυτό, ευχαριστώ, Ευαγγέλιο.'],
    bible: { ref: 'Mark 1:1', koine: 'Ἀρχὴ τοῦ εὐαγγελίου Ἰησοῦ Χριστοῦ', en: 'The beginning of the gospel of Jesus Christ', note: 'εὐαγγέλιον means "good news": εὖ (good) + ἄγγελος (messenger).' },
    know: 'Ευαγγέλιο and άγγελος share a root: an angel is literally a messenger.'
  },
  8: {
    setting: 'Tea time.',
    turn: ['Make tea together and start with Πάμε!', 'Say μπαμπάς and μαμά, and tell each other one memory of your parents.', 'Read άγγελος slowly: ÁN-ge-los.'],
    bible: { ref: 'Luke 2:10', koine: 'καὶ εἶπεν αὐτοῖς ὁ ἄγγελος· μὴ φοβεῖσθε', en: 'And the angel said to them, "Do not be afraid."', note: 'ὁ ἄγγελος, the angel of Christmas night.' },
    know: 'Greeks drink τσάι, but far more καφές. Greek coffee is boiled in a small pot called a μπρίκι.'
  },
  9: {
    setting: 'Reading signs.',
    turn: ['Find three things at home whose English names come from Greek.', 'Say Δόξα τω Θεώ whenever something good happens today.', 'Read ΘΕΑΤΡΟ, ΜΟΥΣΙΚΗ and ΤΗΛΕΦΩΝΟ in capitals.'],
    bible: { ref: 'Luke 2:14', koine: 'Δόξα ἐν ὑψίστοις θεῷ', en: 'Glory to God in the highest', note: 'The angels\' song. Δόξα τω Θεώ comes from phrases like this.' }
  },
  10: {
    setting: 'Good night.',
    turn: ['Read Ιησούς Χριστός and Ελλάδα aloud together.', 'Make Καληνύχτα, αγάπη μου your good-night words.', 'Read the verse below aloud together, slowly.'],
    bible: { ref: 'John 1:1', koine: 'Ἐν ἀρχῇ ἦν ὁ λόγος', en: 'In the beginning was the Word', note: 'You can now read every letter in this verse.' }
  },
  11: {
    setting: 'Pretend you are meeting for the first time.',
    turn: ['Introduce yourselves with your real names: Με λένε…', 'Ask Πώς σε λένε; and answer.', 'Say Χαίρω πολύ and shake hands.'],
    drills: [
      { s: 'Εγώ ___ καλά.', a: 'είμαι', o: ['είμαι', 'είσαι'], en: 'I am fine.', why: 'With εγώ, the verb is είμαι.' },
      { s: 'Εσύ ___ καλά;', a: 'είσαι', o: ['είμαι', 'είσαι'], en: 'Are you fine?', why: 'With εσύ, the verb is είσαι.' }
    ],
    spot: { w: ['Εσύ', 'είμαι', 'καλά;'], wrong: 1, fix: 'είσαι', en: 'Are you fine?', why: 'With εσύ, the verb is είσαι.' },
    know: 'Χαίρω πολύ means "I rejoice a lot". It shares its root with χαρά, joy.'
  },
  12: {
    setting: 'A friend visits. Introduce each other.',
    turn: ['Introduce each other to an imaginary guest.', 'Point at people in a family photo: Αυτός είναι… / Αυτή είναι…', 'Say ο άντρας μου or η γυναίκα μου, whichever fits you.'],
    drills: [
      { s: '___ άντρας μου', a: 'ο', o: ['ο', 'η'], en: 'my husband', why: 'άντρας is masculine: ο.' },
      { s: '___ γυναίκα μου', a: 'η', o: ['ο', 'η'], en: 'my wife', why: 'γυναίκα is feminine: η.' }
    ],
    spot: { w: ['Αυτός', 'είναι', 'η', 'γυναίκα', 'μου.'], wrong: 0, fix: 'Αυτή', en: 'This is my wife.', why: 'For a woman, "this" is αυτή.' },
    bible: { ref: 'Ephesians 5:25', koine: 'Οἱ ἄνδρες, ἀγαπᾶτε τὰς γυναῖκας', en: 'Husbands, love your wives', note: 'ἄνδρες and γυναῖκας are the plurals of today\'s άντρας and γυναίκα.' }
  },
  13: {
    setting: 'Sunday evening. One of you comes home from work.',
    turn: ['Ask each other Πώς είσαι; and answer honestly, with your own ending.', 'Name one feeling from your day, then say why in English or Telugu.', 'Finish with Είμαι χαρούμενος / χαρούμενη γιατί είμαστε μαζί.'],
    table: { tone: 'gender', cols: ['A man says', 'A woman says'], rows: [['χαρούμενος', 'χαρούμενη'], ['κουρασμένος', 'κουρασμένη'], ['λυπημένος', 'λυπημένη'], ['ήρεμος', 'ήρεμη']] },
    drills: [
      { s: 'Ο άντρας μου είναι χαρούμεν___.', a: 'ος', o: ['ος', 'η'], en: 'My husband is happy.', why: 'A man: -ος.' },
      { s: 'Η γυναίκα μου είναι ήρεμ___.', a: 'η', o: ['ος', 'η'], en: 'My wife is calm.', why: 'A woman: -η.' }
    ],
    spot: { w: ['Η', 'γυναίκα', 'μου', 'είναι', 'κουρασμένος.'], wrong: 4, fix: 'κουρασμένη', en: 'My wife is tired.', why: 'She is a woman, so the ending is -η.' },
    bible: { ref: 'Galatians 5:22', koine: 'ὁ δὲ καρπὸς τοῦ πνεύματός ἐστιν ἀγάπη, χαρά, εἰρήνη', en: 'But the fruit of the Spirit is love, joy, peace', note: 'χαρούμενος (joyful) comes from χαρά. λυπημένος comes from λύπη, the sorrow Jesus felt in Gethsemane (Matthew 26:38).' },
    know: 'Greeks rarely answer "fine" automatically. Έτσι κι έτσι ("so-so") is a normal, honest answer.'
  },
  14: {
    setting: 'Looking for things around the house.',
    turn: ['Point at things and ask Τι είναι αυτό;', 'Hide something and ask Πού είναι…; Answer Εδώ! or Εκεί!', 'Ask each other one real Γιατί; question.'],
    drills: [
      { s: '___ είσαι; (Where are you?)', a: 'Πού', o: ['Πού', 'Πώς', 'Τι'], en: 'Where are you?', why: 'πού means where.' },
      { s: '___ είσαι; (How are you?)', a: 'Πώς', o: ['Πού', 'Πώς', 'Τι'], en: 'How are you?', why: 'πώς means how.' }
    ],
    bible: { ref: 'John 1:38', koine: 'Ῥαββί… ποῦ μένεις;', en: 'Rabbi… where are you staying?', note: 'ποῦ is today\'s πού. The first question the disciples asked Jesus.' }
  },
  15: {
    setting: 'Checking plans for the evening.',
    turn: ['Ask each other three yes/no questions and answer with δεν.', 'Answer one question with ίσως and one with βέβαια.', 'Say Δεν ξέρω honestly about something.'],
    drills: [
      { s: '___ ξέρω.', a: 'Δεν', o: ['Δεν', 'Όχι'], en: 'I don\'t know.', why: 'δεν goes before a verb.' },
      { s: 'Όχι, ___ είμαι κουρασμένη.', a: 'δεν', o: ['δεν', 'όχι'], en: 'No, I\'m not tired.', why: 'Όχι answers the question; δεν makes the verb negative.' }
    ],
    know: 'Greeks often use both together: Όχι, δεν ξέρω. "No, I don\'t know."'
  },
  16: {
    setting: 'Sitting together on a quiet evening.',
    turn: ['Hold hands and say Είμαστε μαζί.', 'Point at a family photo: Αυτοί είναι…', 'Greet an imagined elder politely: Πώς είστε;'],
    table: { tone: 'plain', cols: ['Who', 'is / are'], rows: [['εγώ', 'είμαι'], ['εσύ', 'είσαι'], ['αυτός / αυτή', 'είναι'], ['εμείς', 'είμαστε'], ['εσείς', 'είστε'], ['αυτοί', 'είναι']] },
    drills: [
      { s: 'Εμείς ___ μαζί.', a: 'είμαστε', o: ['είμαστε', 'είστε', 'είναι'], en: 'We are together.', why: 'εμείς → είμαστε.' },
      { s: 'Εσείς ___ καλά;', a: 'είστε', o: ['είμαστε', 'είστε', 'είναι'], en: 'Are you (all) well?', why: 'εσείς → είστε.' }
    ],
    bible: { ref: 'Matthew 18:20', koine: 'οὗ γάρ εἰσιν δύο ἢ τρεῖς συνηγμένοι εἰς τὸ ἐμὸν ὄνομα, ἐκεῖ εἰμι ἐν μέσῳ αὐτῶν', en: 'For where two or three are gathered in my name, there am I among them.', note: 'εἰσιν (they are) and εἰμι (I am) are the old forms of είναι and είμαι.' }
  },
  17: {
    setting: 'Counting things on the table.',
    turn: ['Count spoons, cups and fingers together, in Greek.', 'Ask Πόσα; about things in the room and answer.', 'Count backwards from πέντε to ένα.'],
    bible: { ref: 'John 6:9', koine: 'πέντε ἄρτους κριθίνους καὶ δύο ὀψάρια', en: 'five barley loaves and two fish', note: 'πέντε and δύο are the numbers you just learned.' }
  },
  18: {
    setting: 'Getting ready to leave the house.',
    turn: ['Ask Τι ώρα είναι; three times today.', 'Say the time right now: Είναι…', 'Count from one to ten together, taking turns.'],
    bible: { ref: 'Matthew 18:22', koine: 'ἕως ἑβδομηκοντάκις ἑπτά', en: 'seventy times seven', note: 'ἑπτά is επτά, the formal spelling of εφτά. Jesus on forgiveness.' }
  },
  19: {
    setting: 'A message in the middle of the day.',
    turn: ['Send one of today\'s phrases to each other on WhatsApp, in Greek.', 'Say Είσαι όμορφη / όμορφος with the right ending.', 'Tell each other Είμαι τυχερός / τυχερή.'],
    drills: [
      { s: 'Είσαι όμορφ___! (to her)', a: 'η', o: ['ος', 'η'], en: 'You are beautiful!', why: 'To a woman: -η.' },
      { s: 'Είμαι τυχερ___. (a man)', a: 'ός', o: ['ός', 'ή'], en: 'I am lucky.', why: 'A man: -ός.' }
    ],
    bible: { ref: 'Song of Songs 4:1', koine: 'Ἰδοὺ εἶ καλή, ἡ πλησίον μου', en: 'Behold, you are beautiful, my love', note: 'From the Septuagint, the Greek Old Testament. εἶ is the old form of είσαι.' }
  },
  20: {
    setting: 'Breakfast, all in Greek.',
    turn: ['Do the breakfast dialogue at the real table tomorrow.', 'Ask Κοιμήθηκες καλά; every morning this week.', 'Add one thing of your own to the conversation.'],
    know: 'You now know about 70 Greek words and phrases. That is enough for a real breakfast conversation.'
  },
  21: {
    setting: 'Planning a coffee date.',
    turn: ['Ask Έχεις χρόνο; and plan a real coffee date.', 'Say one thing you have: Έχω…', 'Say one thing you don\'t have: Δεν έχω…'],
    table: { tone: 'plain', cols: ['Who', 'have'], rows: [['εγώ', 'έχω'], ['εσύ', 'έχεις'], ['αυτός / αυτή', 'έχει'], ['εμείς', 'έχουμε'], ['εσείς', 'έχετε'], ['αυτοί', 'έχουν']] },
    drills: [
      { s: 'Εγώ ___ χρόνο.', a: 'έχω', o: ['έχω', 'έχεις', 'έχει'], en: 'I have time.', why: 'εγώ → έχω.' },
      { s: 'Εσύ ___ χρόνο;', a: 'έχεις', o: ['έχω', 'έχεις', 'έχει'], en: 'Do you have time?', why: 'εσύ → έχεις.' }
    ],
    bible: { ref: 'John 3:16', koine: 'ἀλλ᾽ ἔχῃ ζωὴν αἰώνιον', en: 'but have eternal life', note: 'ἔχῃ is a form of έχω, "I have".' }
  },
  22: {
    setting: 'Walking around the house.',
    turn: ['Walk around the house and name things with ο, η or το.', 'Ask Πού είναι…; about three things.', 'Guess the gender of a new word from its ending.'],
    table: { tone: 'plain', cols: ['ο', 'η', 'το'], rows: [['ο καφές', 'η πόρτα', 'το νερό'], ['ο κήπος', 'η κουζίνα', 'το σπίτι'], ['-ος -ας -ης', '-α -η', '-ο -ι -μα']] },
    drills: [
      { s: '___ καφές', a: 'ο', o: ['ο', 'η', 'το'], en: 'the coffee', why: '-ς ending: masculine, ο.' },
      { s: '___ πόρτα', a: 'η', o: ['ο', 'η', 'το'], en: 'the door', why: '-α ending: feminine, η.' },
      { s: '___ νερό', a: 'το', o: ['ο', 'η', 'το'], en: 'the water', why: '-ο ending: neuter, το.' }
    ],
    know: 'Even things have a gender in Greek: coffee is masculine, the door feminine, water neuter.'
  },
  23: {
    setting: 'Making drinks for each other.',
    turn: ['Make each other a drink, asking only in Greek.', 'Say three things you want: Θέλω…', 'Say one thing you don\'t want: Δεν θέλω…'],
    drills: [
      { s: 'Θέλω καφ___, παρακαλώ.', a: 'έ', o: ['έ', 'ές'], en: 'I want coffee, please.', why: 'After θέλω, ο καφές drops its ς.' },
      { s: '___ καφέ ή τσάι;', a: 'Θέλεις', o: ['Θέλω', 'Θέλεις'], en: 'Do you want coffee or tea?', why: 'Asking "you": θέλεις.' }
    ],
    spot: { w: ['Θέλω', 'καφές,', 'παρακαλώ.'], wrong: 1, fix: 'καφέ,', en: 'I want coffee, please.', why: 'After θέλω, ο καφές drops its ς: θέλω καφέ.' },
    bible: { ref: 'John 4:7', koine: 'Δός μοι πεῖν', en: 'Give me a drink', note: 'Jesus to the Samaritan woman at the well.' }
  },
  24: {
    setting: 'Deciding tomorrow\'s dinner.',
    turn: ['Decide tomorrow\'s dinner in Greek.', 'Name everything on your plate tonight.', 'Say how many: δύο αυγά, τρία ψάρια.'],
    drills: [
      { s: 'δύο αυγ___', a: 'ά', o: ['ό', 'ά'], en: 'two eggs', why: 'το αυγό → τα αυγά.' },
      { s: 'τρία ψάρι___', a: 'α', o: ['ες', 'α'], en: 'three fish', why: 'το ψάρι → τα ψάρια.' }
    ],
    bible: { ref: 'Luke 24:42', koine: 'οἱ δὲ ἐπέδωκαν αὐτῷ ἰχθύος ὀπτοῦ μέρος', en: 'They gave him a piece of broiled fish.', note: 'The Bible word for fish is ἰχθύς, the ΙΧΘΥΣ fish symbol of early Christians. Today Greeks say ψάρι.' }
  },
  25: {
    setting: 'Dinner is ready.',
    turn: ['Use these phrases at tonight\'s dinner.', 'Offer Κι άλλο; and answer honestly.', 'Say Πεινάω before dinner and Χόρτασα after.'],
    drills: [
      { s: 'Εσύ ___; (Are you hungry?)', a: 'πεινάς', o: ['πεινάω', 'πεινάς'], en: 'Are you hungry?', why: 'εσύ → πεινάς.' }
    ],
    bible: { ref: 'Matthew 5:6', koine: 'μακάριοι οἱ πεινῶντες καὶ διψῶντες τὴν δικαιοσύνην', en: 'Blessed are those who hunger and thirst for righteousness', note: 'πεινῶντες and διψῶντες come from πεινάω and διψάω.' },
    know: 'Καλή όρεξη ("good appetite") is said at the start of every Greek meal.'
  },
  26: {
    setting: 'Calling each other from different rooms.',
    turn: ['Call each other from different rooms, in Greek only.', 'Say where you are right now: Είμαι στο… / στην…', 'Say Έλα εδώ! and see if your spouse comes.'],
    drills: [
      { s: 'Είμαι ___ κουζίνα.', a: 'στην', o: ['στο', 'στην'], en: 'I\'m in the kitchen.', why: 'η κουζίνα → στην κουζίνα.' },
      { s: 'Είμαι ___ σαλόνι.', a: 'στο', o: ['στο', 'στην'], en: 'I\'m in the living room.', why: 'το σαλόνι → στο σαλόνι.' }
    ],
    spot: { w: ['Είμαι', 'στο', 'κουζίνα.'], wrong: 1, fix: 'στην', en: 'I\'m in the kitchen.', why: 'η κουζίνα is feminine, so στην.' }
  },
  27: {
    setting: 'Looking for the keys, again.',
    turn: ['Hide the keys and ask for them in Greek.', 'Name three things on the table.', 'Say the plurals: η καρέκλα → οι καρέκλες.'],
    drills: [
      { s: 'η καρέκλα → οι καρέκλ___', a: 'ες', o: ['ες', 'α'], en: 'the chairs', why: '-α → -ες.' },
      { s: '___ κλειδιά', a: 'τα', o: ['τα', 'οι'], en: 'the keys', why: 'το κλειδί → τα κλειδιά.' }
    ],
    bible: { ref: 'Matthew 16:19', koine: 'δώσω σοι τὰς κλεῖδας τῆς βασιλείας τῶν οὐρανῶν', en: 'I will give you the keys of the kingdom of heaven', note: 'κλεῖδας (keys) is the old form of κλειδιά.' }
  },
  28: {
    setting: 'The tea has gone cold.',
    turn: ['Describe three things on the table: big, small, hot or cold.', 'Admire something: Ωραίο!', 'Say ο μεγάλος…, η μεγάλη…, το μεγάλο… with things in your home.'],
    table: { tone: 'plain', cols: ['ο', 'η', 'το'], rows: [['μεγάλος', 'μεγάλη', 'μεγάλο'], ['μικρός', 'μικρή', 'μικρό'], ['ζεστός', 'ζεστή', 'ζεστό']] },
    drills: [
      { s: 'Το τσάι είναι κρύ___.', a: 'ο', o: ['ος', 'α', 'ο'], en: 'The tea is cold.', why: 'το τσάι is neuter: -ο.' },
      { s: 'Η κουζίνα είναι μεγάλ___.', a: 'η', o: ['ος', 'η', 'ο'], en: 'The kitchen is big.', why: 'η κουζίνα is feminine: -η.' }
    ],
    bible: { ref: 'Revelation 21:5', koine: 'Ἰδοὺ καινὰ ποιῶ πάντα', en: 'Behold, I make all things new', note: 'καινά (new) is the root of today\'s καινούργιος.' }
  },
  29: {
    setting: 'Cooking dinner together.',
    turn: ['Cook one meal this week speaking only Greek.', 'Ask Να βοηθήσω; and actually help.', 'Say who does what: Εγώ μαγειρεύω, εσύ πλένεις.'],
    table: { tone: 'plain', cols: ['Who', 'cook'], rows: [['εγώ', 'μαγειρεύω'], ['εσύ', 'μαγειρεύεις'], ['αυτός / αυτή', 'μαγειρεύει'], ['εμείς', 'μαγειρεύουμε'], ['εσείς', 'μαγειρεύετε'], ['αυτοί', 'μαγειρεύουν']] },
    drills: [
      { s: 'Εμείς μαγειρεύ___ μαζί.', a: 'ουμε', o: ['ουμε', 'ετε', 'ουν'], en: 'We cook together.', why: 'εμείς → -ουμε.' },
      { s: 'Τι μαγειρεύ___; (you)', a: 'εις', o: ['ω', 'εις', 'ει'], en: 'What are you cooking?', why: 'εσύ → -εις.' }
    ],
    bible: { ref: 'John 21:12', koine: 'Δεῦτε ἀριστήσατε', en: 'Come and have breakfast', note: 'The risen Jesus cooks fish for his friends on the shore.' }
  },
  30: {
    setting: 'Evening at home, all in Greek.',
    turn: ['Do the whole evening dialogue tonight when one of you comes home.', 'Pray before dinner, starting with Ας προσευχηθούμε.', 'Ask Πώς πήγε η μέρα σου; and answer with two sentences.'],
    know: 'You have finished the first 30 lessons: about 200 Greek words and phrases.'
  }
};

// Introductions and reading passages. Lessons 1-10 read lines of letters and words;
// from lesson 11 each reading is a short story about Νίκος and Ελένη, a married couple.
// lines: [Greek, English]; gloss: words in the reading not taught yet.
(function (X) {
  var R = {
    1: { intro: 'Greek has 24 letters, and today you meet the vowels. There are seven vowel letters but only five vowel sounds, which makes reading easier than it looks. By the end you will read every vowel and greet each other in Greek.',
      reading: { title: 'Read these aloud', drill: true, lines: [['α · ε · ι · ο', 'a · e · i · o'], ['η · υ · ω', 'i · i · o'], ['ο · ω', 'both are o'], ['ι · η · υ', 'all three are i'], ['Γεια σου!', 'Hi!']] } },
    2: { intro: 'Seven consonants today, most of them familiar from English. Add them to the vowels and you can read your first real Greek words. Watch for ν, which looks like v but is n.',
      reading: { title: 'Read these aloud', drill: true, lines: [['μα · να · τα · πα · λα · σα', 'ma · na · ta · pa · la · sa'], ['καλό', 'good'], ['όνομα', 'name'], ['μέλι', 'honey'], ['πότε', 'when'], ['Καλημέρα!', 'Good morning!']] } },
    3: { intro: 'Four letters that look like English letters but sound different. Most learners trip over these for a week or two; reading them aloud every day fixes it. You also learn to say please and thank you.',
      reading: { title: 'Read these aloud', drill: true, lines: [['ρα · βα · γα · δα', 'ra · va · gha · dha'], ['νερό · γάλα · δρόμος', 'water · milk · road'], ['βιβλίο', 'book'], ['Νερό, παρακαλώ.', 'Water, please.'], ['Ευχαριστώ!', 'Thank you!'], ['Παρακαλώ.', 'You\'re welcome.']] } },
    4: { intro: 'Six letters with new shapes, each standing for a sound English writes with two letters. With these you know almost the whole alphabet, including the letters of Θεός, God.',
      reading: { title: 'Read these aloud', drill: true, lines: [['θα · φα · χα · ψα · ξα · ζα', 'tha · fa · kha · psa · ksa · za'], ['Θεός · ζωή · ψωμί', 'God · life · bread'], ['φίλος · χαρά', 'friend · joy'], ['Ψωμί; Ναι.', 'Bread? Yes.'], ['Γάλα; Όχι.', 'Milk? No.']] } },
    5: { intro: 'Greek words have one loud syllable, and the accent mark shows which. Moving it can change the meaning, so today you train your ear for stress. You also learn the three most important words in any language.',
      reading: { title: 'Read these aloud', drill: true, lines: [['πότε — ποτέ', 'when — never'], ['όνομα · καλό · νερό', 'Ó-no-ma · ka-LÓ · ne-RÓ'], ['Πότε;', 'When?'], ['Ποτέ!', 'Never!'], ['Σ\' αγαπώ.', 'I love you.'], ['Κι εγώ.', 'Me too.']] } },
    6: { intro: 'Some sounds are written with two letters together. Today you learn four of these pairs, and your first short conversation: asking how someone is.',
      reading: { title: 'Read these aloud', drill: true, lines: [['ου · ει · οι · αι', 'u · i · i · e'], ['ουρανός', 'heaven'], ['είμαι · και', 'I am · and'], ['Τι κάνεις;', 'How are you?'], ['Καλά, εσύ;', 'Good, and you?'], ['Καλά, ευχαριστώ.', 'Good, thank you.']] } },
    7: { intro: 'Two more pairs, αυ and ευ, which sound like av and ev, or af and ef. You will see them in some of the most important words in the Bible, including Ευαγγέλιο, the Gospel.',
      reading: { title: 'Read these aloud', drill: true, lines: [['αύριο · αυτό', 'ÁV-ri-o · af-TÓ'], ['Ευαγγέλιο · ευχαριστώ', 'ev-an-GÉ-li-o · ef-kha-ri-STÓ'], ['Συγγνώμη!', 'Sorry!'], ['Δεν πειράζει.', 'No problem.'], ['Τα λέμε αύριο.', 'See you tomorrow.']] } },
    8: { intro: 'Modern Greek has no single letters for b, d and g, so it uses pairs. After today you can read every Greek spelling. Tea is on the menu.',
      reading: { title: 'Read these aloud', drill: true, lines: [['μπα · ντα · γκα · τσα · τζα', 'ba · da · ga · tsa · dza'], ['μπαμπάς · μαμά', 'dad · mum'], ['τσάι · άγγελος', 'tea · angel'], ['Τσάι, μαμά;', 'Tea, mum?'], ['Ναι, ευχαριστώ.', 'Yes, thank you.'], ['Πάμε!', 'Let\'s go!']] } },
    9: { intro: 'You already know hundreds of Greek words, because English borrowed them. Today you read them the Greek way, and learn to read capital letters, the way Greek signs are written.',
      reading: { title: 'Read these aloud', drill: true, lines: [['τηλέφωνο · μουσική · θέατρο', 'telephone · music · theatre'], ['πρόβλημα · ιδέα', 'problem · idea'], ['ΑΘΗΝΑ · ΘΕΑΤΡΟ', 'Athens · theatre'], ['Καλή ιδέα!', 'Good idea!'], ['Δόξα τω Θεώ!', 'Thank God!']] } },
    10: { intro: 'The first checkpoint. You now know every letter and every letter pair, so any Greek word can be read aloud. Today you read names, places and your first Bible verse.',
      reading: { title: 'Read these aloud', drill: true, lines: [['Ελλάδα · Αθήνα', 'Greece · Athens'], ['Ιησούς Χριστός', 'Jesus Christ'], ['Η Βίβλος', 'The Bible'], ['Ἐν ἀρχῇ ἦν ὁ λόγος.', 'In the beginning was the Word. (John 1:1)'], ['Καληνύχτα, αγάπη μου.', 'Good night, my love.'], ['Ο Θεός μαζί σου.', 'God be with you.']] } },
    11: { intro: 'From this lesson on, each chapter has a short reading about Νίκος and Ελένη, a married couple much like you. Today, many years ago, they meet for the first time. You learn to say who you are and to ask a name.',
      reading: { title: 'The first meeting', lines: [['Γεια σου! Με λένε Νίκο.', 'Hi! My name is Nikos.'], ['Είμαι ο Νίκος.', 'I am Nikos.'], ['Εσύ; Πώς σε λένε;', 'And you? What\'s your name?'], ['Με λένε Ελένη.', 'My name is Eleni.'], ['Χαίρω πολύ, Ελένη!', 'Nice to meet you, Eleni!'], ['Κι εγώ, Νίκο.', 'Me too, Nikos.']],
        gloss: [['Νίκο', 'Nikos, when someone names him or talks to him']] } },
    12: { intro: 'Today Nikos and Eleni are married, and they introduce each other to a friend. You learn he and she, and the two words for "the": ο for him and η for her.',
      reading: { title: 'Meet my wife', lines: [['Αυτός είναι ο Νίκος.', 'This is Nikos.'], ['Αυτή είναι η Ελένη.', 'This is Eleni.'], ['Ο Νίκος λέει: «Αυτή είναι η γυναίκα μου.»', 'Nikos says: "This is my wife."'], ['Η Ελένη λέει: «Και αυτός είναι ο άντρας μου.»', 'Eleni says: "And this is my husband."'], ['Ο φίλος τους λέει: «Χαίρω πολύ!»', 'Their friend says: "Nice to meet you!"']],
        gloss: [['λέει', 'says'], ['ο φίλος', 'the friend'], ['τους', 'their']] } },
    13: { intro: 'How are you feeling? In Greek, the answer changes depending on whether a man or a woman is speaking. Telugu does something very similar, so this will feel natural.',
      reading: { title: 'Sunday evening', lines: [['Είναι Κυριακή βράδυ.', 'It is Sunday evening.'], ['Ο Νίκος είναι στο σπίτι.', 'Nikos is at home.'], ['Η Ελένη έρχεται.', 'Eleni comes in.'], ['«Γεια σου, αγάπη μου! Πώς είσαι;»', '"Hi, my love! How are you?"'], ['«Είμαι κουρασμένη. Εσύ;»', '"I\'m tired. You?"'], ['«Εγώ είμαι χαρούμενος. Και ήρεμος.»', '"I\'m happy. And calm."'], ['Η Ελένη δεν είναι λυπημένη. Είναι απλώς κουρασμένη.', 'Eleni isn\'t sad. She is just tired.']],
        gloss: [['Κυριακή', 'Sunday'], ['βράδυ', 'evening'], ['στο σπίτι', 'at home'], ['έρχεται', 'comes'], ['δεν', 'not'], ['απλώς', 'just']] } },
    14: { intro: 'Questions keep a conversation going. Today you learn where, how, who, why and what, and how Greek marks a question with a sign that looks like a semicolon.',
      reading: { title: 'Where is the phone?', lines: [['Η Ελένη ψάχνει κάτι.', 'Eleni is looking for something.'], ['«Νίκο, πού είναι το τηλέφωνο;»', '"Nikos, where is the phone?"'], ['«Εκεί!»', '"There!"'], ['«Πού; Εδώ;»', '"Where? Here?"'], ['«Όχι, εκεί!»', '"No, there!"'], ['«Α, ναι! Και τι είναι αυτό;»', '"Ah, yes! And what is this?"'], ['«Είναι το βιβλίο μου.»', '"It\'s my book."']],
        gloss: [['ψάχνει', 'is looking for'], ['κάτι', 'something'], ['το βιβλίο', 'the book']] } },
    15: { intro: 'Saying no, not, maybe and of course. Greek puts δεν in front of the verb, where Telugu puts "not" at the end.',
      reading: { title: 'Saturday plans', lines: [['Είναι Σάββατο.', 'It is Saturday.'], ['«Είσαι κουρασμένος;» ρωτάει η Ελένη.', '"Are you tired?" Eleni asks.'], ['«Όχι, δεν είμαι κουρασμένος.»', '"No, I\'m not tired."'], ['«Πάμε για καφέ;»', '"Shall we go for coffee?"'], ['«Ίσως… Δεν ξέρω.»', '"Maybe… I don\'t know."'], ['«Νίκο!»', '"Nikos!"'], ['«Εντάξει, βέβαια! Πάμε!»', '"OK, of course! Let\'s go!"']],
        gloss: [['Σάββατο', 'Saturday'], ['ρωτάει', 'asks'], ['για καφέ', 'for coffee']] } },
    16: { intro: 'We, you (plural) and they, and the whole verb "to be". You also learn μαζί, together, the word this app is named after.',
      reading: { title: 'At church', lines: [['Ο Νίκος και η Ελένη είναι μαζί δέκα χρόνια.', 'Nikos and Eleni have been together for ten years.'], ['Σήμερα είναι στην εκκλησία.', 'Today they are at church.'], ['Ένας φίλος λέει: «Πώς είστε;»', 'A friend says: "How are you both?"'], ['«Είμαστε καλά, ευχαριστώ. Εσείς;»', '"We are well, thank you. And you?"'], ['«Κι εμείς είμαστε καλά. Δόξα τω Θεώ!»', '"We are well too. Thank God!"']],
        gloss: [['δέκα χρόνια', 'ten years'], ['σήμερα', 'today'], ['στην εκκλησία', 'at church'], ['ένας φίλος', 'a friend']] } },
    17: { intro: 'The numbers one to five. You will notice they sound like their Sanskrit cousins, which you already know from Telugu words.',
      reading: { title: 'Counting eggs', lines: [['Η Ελένη μετράει.', 'Eleni is counting.'], ['«Ένα, δύο, τρία, τέσσερα, πέντε.»', '"One, two, three, four, five."'], ['«Πόσα;» ρωτάει ο Νίκος.', '"How many?" asks Nikos.'], ['«Πέντε αυγά.»', '"Five eggs."'], ['«Πέντε; Όχι, τέσσερα!»', '"Five? No, four!"'], ['«Α, ναι. Τέσσερα.»', '"Ah, yes. Four."']],
        gloss: [['μετράει', 'is counting'], ['αυγά', 'eggs']] } },
    18: { intro: 'The numbers six to ten, and how to ask and tell the time. After today you can count to ten and plan when to leave.',
      reading: { title: 'Sunday morning', lines: [['Είναι Κυριακή πρωί.', 'It is Sunday morning.'], ['«Τι ώρα είναι;» ρωτάει η Ελένη.', '"What time is it?" asks Eleni.'], ['«Είναι εννιά.»', '"It\'s nine."'], ['«Εννιά; Η εκκλησία είναι στις δέκα!»', '"Nine? Church is at ten!"'], ['«Εντάξει, έχουμε χρόνο.»', '"OK, we have time."'], ['«Όχι πολύ! Πάμε!»', '"Not much! Let\'s go!"']],
        gloss: [['πρωί', 'morning'], ['στις δέκα', 'at ten'], ['έχουμε χρόνο', 'we have time']] } },
    19: { intro: 'Words of love. You learn how Greek couples talk to each other, and a small word, μου, that means both "my" and "to me".',
      reading: { title: 'A message from work', lines: [['Ο Νίκος είναι στη δουλειά.', 'Nikos is at work.'], ['Γράφει στην Ελένη:', 'He writes to Eleni:'], ['«Μου λείπεις, καρδιά μου.»', '"I miss you, sweetheart."'], ['Η Ελένη γράφει: «Κι εσύ μου λείπεις, μωρό μου.»', 'Eleni writes: "I miss you too, my baby."'], ['«Είμαι τυχερός που σε έχω.»', '"I\'m lucky to have you."'], ['«Κι εγώ είμαι τυχερή. Φιλάκια!»', '"I\'m lucky too. Kisses!"']],
        gloss: [['στη δουλειά', 'at work'], ['γράφει', 'writes'], ['που σε έχω', 'to have you']] } },
    20: { intro: 'The second checkpoint. Everything from the last ten lessons comes together in one breakfast conversation, and you will understand all of it.',
      reading: { title: 'Breakfast', lines: [['Είναι πρωί. Ο Νίκος και η Ελένη είναι στην κουζίνα.', 'It is morning. Nikos and Eleni are in the kitchen.'], ['«Καλημέρα, αγάπη μου! Κοιμήθηκες καλά;»', '"Good morning, my love! Did you sleep well?"'], ['«Ναι, πολύ καλά. Εσύ;»', '"Yes, very well. You?"'], ['«Όχι πολύ. Είμαι λίγο κουρασμένος.»', '"Not really. I\'m a little tired."'], ['«Τσάι;» «Ναι, ευχαριστώ.»', '"Tea?" "Yes, thank you."'], ['«Καλή όρεξη!»', '"Enjoy your breakfast!"'], ['Η Ελένη είναι χαρούμενη. Ο Νίκος είναι κουρασμένος, αλλά χαρούμενος.', 'Eleni is happy. Nikos is tired, but happy.']],
        gloss: [['στην κουζίνα', 'in the kitchen'], ['λίγο', 'a little'], ['αλλά', 'but']] } },
    21: { intro: 'A new unit: home and food. It starts with one of the most useful verbs, έχω, "I have", and with it the pattern most Greek verbs follow.',
      reading: { title: 'An idea', lines: [['Ο Νίκος έχει μια ιδέα.', 'Nikos has an idea.'], ['«Ελένη, έχεις χρόνο σήμερα;»', '"Eleni, do you have time today?"'], ['«Ναι, έχω. Γιατί;»', '"Yes, I do. Why?"'], ['«Πάμε για καφέ;»', '"Shall we go for coffee?"'], ['«Καλή ιδέα! Αλλά δεν έχω πολύ χρόνο.»', '"Good idea! But I don\'t have much time."'], ['«Δεν πειράζει. Ένας καφές, μία ώρα.»', '"No problem. One coffee, one hour."']],
        gloss: [['μια / μία', 'a, one (for η-words)'], ['ένας', 'a, one (for ο-words)'], ['σήμερα', 'today']] } },
    22: { intro: 'Every Greek noun is masculine, feminine or neuter, even a door or a glass of water. Today you learn to tell which from the word\'s ending, and the three words for "the".',
      reading: { title: 'Our house', lines: [['Το σπίτι τους είναι μικρό.', 'Their house is small.'], ['Έχει μια κουζίνα και ένα σαλόνι.', 'It has a kitchen and a living room.'], ['Στην κουζίνα είναι ο καφές και το νερό.', 'The coffee and the water are in the kitchen.'], ['Η πόρτα είναι εκεί, και το παράθυρο εδώ.', 'The door is there, and the window here.'], ['Η Ελένη λέει: «Αγαπώ το σπίτι μας.»', 'Eleni says: "I love our house."']],
        gloss: [['τους', 'their'], ['μικρό', 'small'], ['το σαλόνι', 'the living room'], ['μας', 'our']] } },
    23: { intro: 'Wanting and offering: θέλω, "I want". You also see how a masculine word like ο καφές changes its ending when it is the thing you want.',
      reading: { title: 'Coffee or tea?', lines: [['«Θέλεις καφέ ή τσάι;» ρωτάει ο Νίκος.', '"Do you want coffee or tea?" asks Nikos.'], ['«Θέλω καφέ, παρακαλώ.»', '"I want coffee, please."'], ['«Με ζάχαρη;»', '"With sugar?"'], ['«Λίγο, ευχαριστώ.»', '"A little, thank you."'], ['Ο Νίκος δεν θέλει καφέ. Θέλει τσάι.', 'Nikos doesn\'t want coffee. He wants tea.'], ['«Και νερό, παρακαλώ!» λέει η Ελένη.', '"And water, please!" says Eleni.']],
        gloss: [['με', 'with'], ['θέλει', 'he / she wants']] } },
    24: { intro: 'Everyday food, and how Greek makes plurals: not by adding a syllable like Telugu -లు, but by changing the ending.',
      reading: { title: 'What shall we eat?', lines: [['Τι θέλουν να φάνε απόψε;', 'What do they want to eat tonight?'], ['Ο Νίκος θέλει κοτόπουλο με ρύζι.', 'Nikos wants chicken with rice.'], ['Η Ελένη θέλει ψάρι και λαχανικά.', 'Eleni wants fish and vegetables.'], ['«Και φρούτα;» ρωτάει ο Νίκος.', '"And fruit?" asks Nikos.'], ['«Ναι, βέβαια! Και δύο αυγά για αύριο.»', '"Yes, of course! And two eggs for tomorrow."'], ['«Εντάξει. Πάμε!»', '"OK. Let\'s go!"']],
        gloss: [['θέλουν', 'they want'], ['να φάνε', 'to eat'], ['απόψε', 'tonight'], ['για', 'for']] } },
    25: { intro: 'At the table: hungry, thirsty, tasty, full. These verbs end in -άω, a second verb pattern you will meet often.',
      reading: { title: 'Dinner is ready', lines: [['Είναι οχτώ. Ο Νίκος πεινάει.', 'It\'s eight. Nikos is hungry.'], ['«Πεινάω!» λέει.', '"I\'m hungry!" he says.'], ['«Το φαγητό είναι έτοιμο!» λέει η Ελένη.', '"The food is ready!" says Eleni.'], ['Τρώνε μαζί.', 'They eat together.'], ['«Πολύ νόστιμο!»', '"Very tasty!"'], ['«Κι άλλο;» «Όχι, ευχαριστώ. Χόρτασα.»', '"More?" "No, thank you. I\'m full."']],
        gloss: [['πεινάει', 'is hungry'], ['τρώνε', 'they eat']] } },
    26: { intro: 'Rooms of the house, and the small words στο and στην, "in the". After today you can call each other from room to room in Greek.',
      reading: { title: 'Room to room', lines: [['Ο Νίκος είναι στο σαλόνι. Η Ελένη είναι στην κρεβατοκάμαρα.', 'Nikos is in the living room. Eleni is in the bedroom.'], ['«Ελένη, πού είσαι;»', '"Eleni, where are you?"'], ['«Στην κρεβατοκάμαρα! Εσύ;»', '"In the bedroom! You?"'], ['«Στο σαλόνι. Έλα εδώ!»', '"In the living room. Come here!"'], ['«Γιατί;» «Έχει ωραία μουσική!»', '"Why?" "There\'s lovely music!"'], ['Η Ελένη έρχεται στο σαλόνι.', 'Eleni comes to the living room.']],
        gloss: [['έχει', 'there is'], ['ωραία', 'lovely'], ['έρχεται', 'comes']] } },
    27: { intro: 'Things around the house, and the plural "the": οι and τα. You also get the story of every couple\'s daily search for the keys.',
      reading: { title: 'The keys', lines: [['Ο Νίκος ψάχνει τα κλειδιά του.', 'Nikos is looking for his keys.'], ['«Πού είναι τα κλειδιά;»', '"Where are the keys?"'], ['«Στο τραπέζι;» «Όχι.»', '"On the table?" "No."'], ['«Στην καρέκλα;» «Όχι!»', '"On the chair?" "No!"'], ['«Στο κρεβάτι;» «Όχι…»', '"On the bed?" "No…"'], ['«Νίκο… είναι στην τσάντα σου!»', '"Nikos… they\'re in your bag!"']],
        gloss: [['ψάχνει', 'is looking for'], ['του', 'his'], ['σου', 'your']] } },
    28: { intro: 'Describing words: big, small, hot, cold, new. Like the feelings in lesson 13, they change their ending to match what they describe.',
      reading: { title: 'A new cup', lines: [['Η Ελένη έχει ένα καινούργιο φλιτζάνι.', 'Eleni has a new cup.'], ['Είναι μικρό και πολύ ωραίο.', 'It is small and very pretty.'], ['Ο Νίκος φτιάχνει τσάι.', 'Nikos makes tea.'], ['«Το τσάι είναι ζεστό;» «Όχι, είναι κρύο!»', '"Is the tea hot?" "No, it\'s cold!"'], ['«Συγγνώμη! Θέλεις ζεστό τσάι;»', '"Sorry! Do you want hot tea?"'], ['«Ναι. Σε ένα μεγάλο φλιτζάνι!»', '"Yes. In a big cup!"']],
        gloss: [['το φλιτζάνι', 'the cup'], ['ωραίο', 'pretty, nice'], ['φτιάχνει', 'makes'], ['σε', 'in']] } },
    29: { intro: 'Cooking together, and the full present tense: all six forms of a regular verb. After today you can say who does what in the kitchen.',
      reading: { title: 'Cooking together', lines: [['Απόψε μαγειρεύουν μαζί.', 'Tonight they cook together.'], ['Η Ελένη μαγειρεύει το ψάρι.', 'Eleni cooks the fish.'], ['Ο Νίκος πλένει τα λαχανικά.', 'Nikos washes the vegetables.'], ['«Να βοηθήσω;» ρωτάει ο Νίκος.', '"Shall I help?" asks Nikos.'], ['«Ναι. Πλένεις και τα πιάτα;»', '"Yes. Will you wash the dishes too?"'], ['Ο Νίκος γελάει. «Εντάξει.»', 'Nikos laughs. "OK."']],
        gloss: [['απόψε', 'tonight'], ['τα πιάτα', 'the dishes'], ['γελάει', 'laughs']] } },
    30: { intro: 'The third checkpoint. A whole evening at home: coming back from work, talking about the day, praying and eating together. You know nearly every word.',
      reading: { title: 'Evening at home', lines: [['Είναι βράδυ. Ο Νίκος γυρίζει σπίτι.', 'It is evening. Nikos comes home.'], ['«Γύρισα!»', '"I\'m home!"'], ['«Καλώς ήρθες! Πώς πήγε η μέρα σου;»', '"Welcome home! How was your day?"'], ['«Καλά, αλλά είμαι κουρασμένος. Πεινάω!»', '"Good, but I\'m tired. I\'m hungry!"'], ['«Το φαγητό είναι έτοιμο: ρύζι και κοτόπουλο.»', '"The food is ready: rice and chicken."'], ['Κάθονται στο τραπέζι. «Ας προσευχηθούμε.»', 'They sit at the table. "Let\'s pray."'], ['Μετά τρώνε μαζί, και είναι χαρούμενοι.', 'Afterwards they eat together, and they are happy.']],
        gloss: [['βράδυ', 'evening'], ['γυρίζει', 'comes back'], ['κάθονται', 'they sit'], ['μετά', 'afterwards'], ['χαρούμενοι', 'happy (plural)']] } }
  };
  Object.keys(R).forEach(function (n) { X[n] = X[n] || {}; X[n].intro = R[n].intro; X[n].reading = R[n].reading; });
})(window.MAZI_COURSE.extra);
